### ISSUE TITLE
[Bug] Mod ID conflict with Bonsai Tree Crops mod

### ISSUE THREAD

**Issue by DWX12** [thraaawn/BonsaiTrees#101]
**Bonsai Trees version**: NA
**Forge version**: NA

**Description of the problem including expected versus actual behavior:**

There's a mod id conflict when attempting to use this mod in the same pack as the Bonsai Tree Crops mod:

https://minecraft.curseforge.com/projects/bonsai-tree-crops

**Steps to reproduce:**

Install both BonsaiTrees and Bonsai Tree Crops and run pack.

**Comment by thraaawn** [comment]
They should have named their mod differently. Not much I can do about this.

Not going to change this on my end - way more players would be affected by this, than if that mod changes its modid.

**Comment by DWX12** [comment]
Right, understood, just didn't know if there was some work around for it. I did open up the issue on their end as well.

Thank you for atleast looking at my issue and commenting on it.

**Comment by thraaawn** [comment]
No workarounds as far as I'm aware, sorry :(
