### ISSUE TITLE
Cannot seem to make Pull Request

### ISSUE THREAD

**Issue by katubug** [thraaawn/BonsaiTrees#109]
I've created a bunch of .json files for some Biomes O Plenty dirts, Project Vibrant Journeys trees, etc. I wanted to make you a pull request for them, but the button is greyed out and I can't seem to figure out what I'm doing wrong. I'd appreciate your help.

![ss+(2019-06-03+at+08 46 32)](https://user-images.githubusercontent.com/20935286/58806610-2e717e80-85dc-11e9-8ec6-a238f9847a32.png)

When I try to select anything other than "master" - the "create" button goes completely grey.

Also, quick note: the url in your predefined git issue text (https://vazkii.us/br101/) is a 404.

**Comment by thraaawn** [comment]
Hey, nice. I appreciate it!

To make a Pull Request you need to create a _Fork_ first, i.e. click the fork button on the repositories main page. This will create a copy of the BonsaiTrees repository in your own account. You can modify that by adding and modifying files - it's your repository on your account, so you have full access.
I think the webinterface allows adding files - if not, there is a [windows github client](https://desktop.github.com/) that should be able to do that.

Once you've made all the changes you can create a PR from your copy of the repository.

**Comment by katubug** [comment]
Thank you so much! I'll get that started. Quick question: if I just upload all of my files, can you pick and choose which to add? I've made some options for vanilla cactuses and various mushrooms because I wanted to have potted cactuses and mushrooms - but if you don't want them and can't discard them, I won't upload them.

Thanks again!
