### ISSUE TITLE
Sugar Cane fails when trying to add as a bonsai

### ISSUE THREAD

**Issue by WenXin20** [thraaawn/BonsaiTrees#113]
**Bonsai Trees version**: v1.1.3-b156
**Forge version**: v14.23.5.2838
**Optifine**: Yes
**Link to Crashlog**: None
**Screenshot (if possible)**: Below

**Description of the problem including expected versus actual behavior:**
For my custom modpack, I decided to make sugar cane growable in Bonsai Pots, but am unable to plant the sugar cane into a Bonsai pot. 

The following script fails to work even though it should be correct. The mod doesn't seem to recognize `minecraft:reeds` as an item at all. Changing the sapling to something besides reeds works completely fine, but for some reason, adding reeds doesn't work. 

I have had this problem for a long time now, but only recently realized that it could be a bug.
```
{
    "name": "minecraft:reeds",
    "mod": "minecraft",
    "sapling": {
        "name": "minecraft:reeds",
        "data": 0
    },
    "growTimeMultiplier": 1.5,
    "drops": [
        {
            "name": "minecraft:reeds",
            "data": 0,
            "type": "WOOD"
        },
		{
            "name": "minecraft:reeds",
            "data": 0,
            "type": "SAPLING"
        },
        {
            "name": "minecraft:sugar",
            "data": 0,
            "type": "FRUIT"
        }
    ],
	"compatibleSoilTags": [ "sand", "grass", "dirt" ]
}

```
The following image shows what the output is once I change the `sapling` tag to the `quark:reed_block`. It now registers as a sapling type, but the output doesn't seem to recognize `minecraft:reeds` as a valid item output for `WOOD` or `SAPLING`.
![2019-06-17_01 28 58](https://user-images.githubusercontent.com/12000593/59582960-7a71f800-909f-11e9-803c-6b9b1d34d108.png)
(Just ignore the weird texture bugs from the Dark Theme mod...)

**Steps to reproduce:**
1. Add shapes for sugar cane.
2. Create a types.d file for sugar cane using the above code.
3. Try to plant sugar cane into a Bonsai Pot.

**Comment by WenXin20** [comment]
I found out the same also seems to happen with nether wart

**Comment by Kizzycocoa** [comment]
Was just about to put this, before I saw this. Have been adding all non-standard mushrooms/plants from other mods, as well as the standard Minecraft giant mushrooms. I found this out myself as well. Sugar cane simply cannot be added.
