### ISSUE TITLE
why is mine no hopping bonsai pots

### ISSUE THREAD

**Issue by DioanoDio** [thraaawn/BonsaiTrees#119]
**Read then remove this section**:
Do not create an issue if you have not tried fixing it by using the latest version of the mod!

Also make sure you've read the full readme [here](https://github.com/thraaawn/BonsaiTrees/blob/master/README.md) on github.

**Bonsai Trees version**:1.1.3
**Forge version**:1.12.2
**I am not using Optifine**:no
**Link to Crashlog**: [here](url)
**Screenshot (if possible)**: [here](url)
![2019-09-08_12 16 28](https://user-images.githubusercontent.com/55042507/64483776-a631f380-d232-11e9-8daa-c102dcfd2a9a.png)

**Description of the problem including expected versus actual behavior:**

**Steps to reproduce:**

**Comment by DioanoDio** [comment]
why is mine no hopping bonsai pots

**Comment by thraaawn** [comment]
Yeah, not able to reproduce this. Is it disabled in the pack you are playing?
