### ISSUE TITLE
Support for Dynamic trees?

### ISSUE THREAD

**Issue by TechieJunk** [thraaawn/BonsaiTrees#12]
https://minecraft.curseforge.com/projects/dynamictrees

These trees would look really good in bonsai form.

**Comment by thraaawn** [comment]
Sorry, not possible. That's a whole other tree growing thing that I can't properly replicate without basically reinventing that mod, but just in a single block space.

**Comment by TechieJunk** [comment]
I appreciate the response and understand, thank you for looking into it :)
