### ISSUE TITLE
Permission Issue

### ISSUE THREAD

**Issue by CritFlaw** [thraaawn/BonsaiTrees#120]
**Bonsai Trees version**:
bonsaitrees-1.1.3-b156

**Forge version**:
forge-14.23.5.2847

**I am not using Optifine**:
I am using it, but the bug isn't visual.

**Link to Crashlog**: [here](url)
N/A

**Screenshot (if possible)**: [here](url)
I can post one but it just says "You do not have the permission to use this command."

**Description of the problem including expected versus actual behavior:**
When trying to run `/bonsaitrees generateMissingShapes yes` I get the above error. I've tried on two separate flatworld worlds, cheats enabled. Not sure what the issue is.

**Steps to reproduce:**
1. Create Flatworld world
2. Look at the ground
3. Run `//bonsaitrees generateMissingShapes` yes command

I know this issue has been opened before but I didn't see a resolution. Any updates on this? Am I being dumb with something?

**Comment by daywalker78** [comment]
I had the same problem, it worked once I set the gamemode to Creative.

**Comment by CritFlaw** [comment]
I figured it out. I was doing it wrong.
