### ISSUE TITLE
[Issue] Hopping Bonsai Pot Duplication

### ISSUE THREAD

**Issue by CritFlaw** [thraaawn/BonsaiTrees#123]
Also make sure you've read the full readme [here](https://github.com/thraaawn/BonsaiTrees/blob/master/README.md) on github.

**Bonsai Trees version**:1.1.3-b156
**Forge version**:2847
**I am not using Optifine**: I am using it
**Link to Crashlog**: N/A
**Screenshot (if possible)**: N/A
**Description of the problem including expected versus actual behavior:**
When breaking a hopping bonsai pot with an axe, two are returned

**Steps to reproduce:**
See above

**Comment by CritFlaw** [comment]
Any update..?

**Comment by thraaawn** [comment]
I can not reproduce this. Must be an interaction with some other mod.

**Comment by CritFlaw** [comment]
Turns out it was multi mine causing a bunch of dupe bugs
