### ISSUE TITLE
[Issue] Creating Custom Trees

### ISSUE THREAD

**Issue by CritFlaw** [thraaawn/BonsaiTrees#125]
**Bonsai Trees version**: bonsaitrees-1.1.3-b156
**Forge version**: 14.23.5.2847
**I am not using Optifine**: I **am** using Optifine
**Link to Crashlog**: N/A
**Screenshot (if possible)**: N/A

**Description of the problem including expected versus actual behavior:**
Using the command "/bonsaitrees generateMissingShapes yes" Doe not work. In a flat-world, survival or creative, looking down, does not do anything. It generates nothing in the specified folder. 

**Steps to reproduce:**
Follow steps in the guide. Maybe add Natura as the Redwood is what I'm trying to add.

**Comment by thraaawn** [comment]
The generateMissingShapes command only works for a small subset of mods adding trees.
You mostly have to do them manually. How to do that is also included in the readme.
