### ISSUE TITLE
Breaking hopping bonsai gives 2 back

### ISSUE THREAD

**Issue by Myth-1300** [thraaawn/BonsaiTrees#128]
**Description of the problem including expected versus actual behavior:**
I made 2 hopping bonsais and threw them on a chest and i wanted to move it to a better place so i broke both bonsai hoppers and had 4 in my inventory and it kept going
**Steps to reproduce:**
place hopping bonsai and break it

**Comment by thraaawn** [comment]
Duplicate of #123 
I can not reproduce this. Must be an interaction with some other mod.
