### ISSUE TITLE
Json tree type options

### ISSUE THREAD

**Issue by it-is-I-Pants** [thraaawn/BonsaiTrees#13]
Allowing more config options would be useful when adding new trees. Specifically I'm thinking about the option to set a multiplier instead of just a set value when specifying custom drops and allowing those multipliers to be set on wood types, leaves, etc. I'm working on adding biomes o' plenty support but some trees are huge and I'd like to accommodate that by slowing down the growth of the tree and increasing the drops. Likewise, it'd be nice to lower sapling drops on trees that don't have a lot of leaves. I think I might be able to set it specifically in the json, but it'd be nice to allow it to be adjusted globally in the main config too

**Comment by thraaawn** [comment]
Sorry, I can't follow what you would like to have, please try to be a bit more concise.

Regarding configurability of tree drops in the main config file. No, the json files are just as much a config file as the main config and you can already tweak the drops there. There is no good reason to duplicate a setting.

**Comment by it-is-I-Pants** [comment]
Okay, say the main config file says you get 1 log as a drop with a 50% chance, I'd like if in the individual tree json's I could set it so a tree drops 3x the amount of wood as other trees. Then say I make a pack and adjust the global config to 2 logs per drop instead of one. What I'd like is then for that special tree to automatically drop 6 logs because it's dropping 3 times the amount of the global config. The reason for this is to have more variable growth times for different trees. Not all trees grow at the same speed or give the same amount of resources. I hope I've explained that better
