### ISSUE TITLE
[Suggestion] CurseForge link Broken on Github 

### ISSUE THREAD

**Issue by hyperjoe** [thraaawn/BonsaiTrees#131]
**Bonsai Trees version**: Not Relevant
**Forge version**:  Not Relevant
**I am not using Optifine**: Not Relevant
**Link to Crashlog**: Not Relevant
**Screenshot (if possible)**: Not Relevant

**Description of the problem including expected versus actual behavior:**

If you've pulled your mod off of Curseforge, please remove any links to the "dead" from your Github.

There is still a link to curseforge here:  https://github.com/thraaawn/BonsaiTrees
that takes you to a dead page.

**Comment by theshadowake** [comment]
Can confirm, mod has vanished from CurseForge, meaning I can no longer update my modpack :S

**Comment by davenonymous** [comment]
Yeah. They pulled the mod page because of a link in the description to the Travis CI builds of the mod.
I hope they approve the change soon. Been 24hrs already since it disappeared.
Not going to lie, this is highly demotivating for me as well. Hope they fix it soon.

**Comment by theshadowake** [comment]
I feel you there, the number of times Curse has denied an upload of mine for some completely nonsensical reason. Hope it gets sorted for you soon, I know that Curse approval hell all too well.

Also have a great Xmas :)

**Comment by kreezxil** [comment]
Wow, this happened recently to the LittleTiles by CreativeMD, took curseforge about 2 days to reapprove it.

Who is this Travis CI?

**Comment by kreezxil** [comment]
Ok, found it. https://travis-ci.com/

Really odd that a project that "supports" open source projects is causing projects that link to it on CurseForge to get taken down.

**Comment by BedrockLegends** [comment]
Maybe the Owner of that website asked for the Take down, but who knows at this point.

**Comment by davenonymous** [comment]
Should be fixed now.
