### ISSUE TITLE
Error if The One Probe is not installed

### ISSUE THREAD

**Issue by WenXin20** [thraaawn/BonsaiTrees#133]
`Minecraft v1.14.4`
`Forge v28.1.109`
`Bonsai Pots v2.0.0.30`
`Libnonymous v1.0.0.19`

If The One Probe is not installed, the game will produce an error.
[Log](https://gist.github.com/WenXin20/841724b792a3081c29ffae7f6fd23f2b)
![2020-01-06_15 51 37](https://user-images.githubusercontent.com/12000593/71851831-0af44200-309d-11ea-816f-3ed27f1b4c25.png)

**Comment by LlubNek** [comment]
got a similar error:
![image](https://user-images.githubusercontent.com/313762/71856612-7f85ab80-30b2-11ea-963c-f81a9b838d62.png)
[latest.log](https://github.com/thraaawn/BonsaiTrees/files/4028210/latest.log)

**Comment by davenonymous** [comment]
Fixed with 2c08aba, thanks for the report.
