### ISSUE TITLE
1.14.4 version crashes when Minecraft tires to load up.

### ISSUE THREAD

**Issue by skytheraiders** [thraaawn/BonsaiTrees#135]
[crash-2020-01-07_00.08.39-client.txt](https://github.com/thraaawn/BonsaiTrees/files/4028962/crash-2020-01-07_00.08.39-client.txt)
I tired reinstalling the mod to make sure it wasn't a bad download but it keeps crashing.

**Comment by davenonymous** [comment]
You are missing libnonymous. I've added an appropriate dependency to the 2.0.1 version of the mod.
