### ISSUE TITLE
[Suggestion] Explain how to use the generated files for the sapling maker in the GUI

### ISSUE THREAD

**Issue by Sourpowerpete** [thraaawn/BonsaiTrees#136]
I'm currently stumped on how to use the custom tree I made using the gui for the 1.14.4 version of this mod. Maybe have it explained in the GUI itself?

**Comment by davenonymous** [comment]
The easiest way currently is probably [this](https://www.curseforge.com/minecraft/mc-mods/open-loader) mod by @darkhax.
Then you just have to throw the files in the appropriate subdirectories. Read that mods description for more info.

And yes, an explanation is on the todo list.

**Comment by WenXin20** [comment]
I tried adding some custom trees and then moving it to the data folder using Open Loader, but I couldn't get it to function.

**Comment by davenonymous** [comment]
An explanation is now included in the GUI, along with some error handling.
Update to the latest version 2.1.2 to get those features.
