### ISSUE TITLE
Bonsai Tree Maker GUI Render Issues

### ISSUE THREAD

**Issue by WenXin20** [thraaawn/BonsaiTrees#137]
`Minecraft v1.14.4`
`Forge v28.1.109`
`Bonsai Trees v2.0.0.30`
`JEI v6.0.0.27`

- Item stack numbers & durability bars render incorrectly. 
   - For example, I have a stack of 24 torches in my inventory, but only the parts of the numbers over the item is visible.
- Tabs overlap JEI's Favorites List instead of wrapping around it. 
   - Add to favorites by pressing `a` while hovering over an item.

![2020-01-06_22 54 27](https://user-images.githubusercontent.com/12000593/71916098-c6bb7d00-3142-11ea-8e50-8638b6ce47da.png)

**Comment by WenXin20** [comment]
Also, clicking on an input slot or the tabs will often drop the item being held by the mouse onto the ground.

**Comment by MokahTGS** [comment]
Hey, does this work in 1.14.4?   Are there instructions of how to add trees?  Or am I misunderstanding what this GUI is for.

I tried adding Ferroustry Trees to our server using this GUI but the trees did not work.

**Comment by WenXin20** [comment]
Yes, the GUI works for 1.14+. Once a new tree is added, the file provided has to be placed in a datapack
