### ISSUE TITLE
Can't Plant Sapling on Server

### ISSUE THREAD

**Issue by ThatBenderGuy** [thraaawn/BonsaiTrees#139]
**Bonsai Trees version**: 2.0.1.32
**Forge version**: 28.1.111
**Optifine**: I am using optifine
**Link to Crashlog**: No crashlog
**Screenshot (if possible)**: n/a

**Description of the problem including expected versus actual behavior**:

When I right click on either bonsai pot filled with the correct soil  it just says "Not the correct soil type for this sapling"

**Comment by davenonymous** [comment]
You are not running the latest version of the mod. This has already been fixed. 😃
