### ISSUE TITLE
"unknown error while trying to generate tree shape"

### ISSUE THREAD

**Issue by it-is-I-Pants** [thraaawn/BonsaiTrees#14]
Is there any way to find more information in a log or something? I'd like to be certain that it's not another mod causing this error. This happens on version 1.0.0-b36 when added to the direwolf20 1.12 pack.

**Comment by thraaawn** [comment]
Do you have a log or anything? When does this happen? On startup? When you call the generate shapes command? Why would you not give any information with your issue report - I have no context for your error message, therefore I can not help you.

Anyway, this mod is not generating that error message.

**Comment by it-is-I-Pants** [comment]
Okay this is a screenshot of the message I get and the command that I used
[https://imgur.com/a/ToUdw](url) and here is a copy of the log [https://gist.github.com/it-is-I-Pants/34d9548478ad54bb7d4846ddb7822e2f](url)
