### ISSUE TITLE
[bug?]Olive sapling from lemon sapling

### ISSUE THREAD

**Issue by blank-kiyomi** [thraaawn/BonsaiTrees#142]
Hopping Bonsai Pot in Olive Sapling grows, but drop is Lemon Sapling.
Is this mods bug?
I can't speaking english well. sorry

using versen is
minecraft forge 1.12.2-14.23.5.2847
bonsai trees mod  1.4.4-b170
Heat and Climate Lib 3.2.3
Heat and Climate mod  3.2.5

![2020-01-26_22 03 53](https://user-images.githubusercontent.com/60312486/73144296-c7af5100-40e7-11ea-961a-d807548df2da.png)
![2020-01-26_22 03 42_5](https://user-images.githubusercontent.com/60312486/73144365-63d95800-40e8-11ea-97a1-31d3ebe18fd0.png)

**Comment by davenonymous** [comment]
Yeah, that's a wrong recipe. Needs to be data: 1 in [this](https://github.com/thraaawn/BonsaiTrees/blob/467dcf0114fef23d66bee1c6bf10d4429b127914/src/main/resources/assets/bonsaitrees/config/types.d/hac_olive.json#L22) row. You can change that on your server/client yourself.

I'll fix this once there are a bunch of 1.12 issues that needs fixing. Not going to do a 1.12 release for just this anymore. My 1.12 mods are out of maintenance. Sorry.

**Comment by blank-kiyomi** [comment]
Oh, this is easy fix. I could do it.
This is nice fix.
Thank you!!
![2020-01-27_23 12 35](https://user-images.githubusercontent.com/60312486/73182435-6a091c00-415c-11ea-8a35-e62f53db4b0f.png)
