### ISSUE TITLE
2 issues in v1.15.2

### ISSUE THREAD

**Issue by zodiak246** [thraaawn/BonsaiTrees#144]
1. There is a visual bug where I cant see the trees growing.
![2020-01-31_17 43 23](https://user-images.githubusercontent.com/60527388/73580011-1e9f8800-4452-11ea-9828-668e85080202.png)
2. I tried to use the /bonsai maker but it gave me an error. 
![Bonsai error](https://user-images.githubusercontent.com/60527388/73580061-4b539f80-4452-11ea-86cb-665d1c35e6ca.png)
 Log :
[bonsai-latest.log](https://github.com/thraaawn/BonsaiTrees/files/4142083/bonsai-latest.log)

**Comment by davenonymous** [comment]
Please update to the latest version and retest.

**Comment by zodiak246** [comment]
Unfortunately the second problem still isn't fixed. The mod that im trying to add is Ferroustry

**Comment by davenonymous** [comment]
I don't fully understand when that error is happening.
You've successfully created the json files? But when you try to load them up they don't work? Can you please attach them here, so I can see what's wrong with them?

**Comment by zodiak246** [comment]
[bonsai-exports.zip](https://github.com/thraaawn/BonsaiTrees/files/4142852/bonsai-exports.zip)

this is the files that I got

**Comment by davenonymous** [comment]
The tree models are garbled. Did you make sure the preview looked ok and showed only the tree?
You have to isolate the tree you want to turn into a bonsai completely. No blocks may touch the tree directly or diagonally.

**Comment by zodiak246** [comment]
How can I create a preview? do I have to do it in creative?

this is the preview that I see when I start /bonsai maker
![2020-02-01_12 29 09](https://user-images.githubusercontent.com/60527388/73596230-84d9e880-44ee-11ea-8a6e-63ad484fe4a4.png)

**Comment by davenonymous** [comment]
This is the preview that I'm talking about. It should only show the tree.
Again, you have to make sure the tree is touching nothing.

**Comment by zodiak246** [comment]
Thank You for your assistance. I love this mod and the /bonsai maker that was added. Everything is working now and thank you for being active with quick response. 
![2020-02-01_12 37 06](https://user-images.githubusercontent.com/60527388/73596738-fe73d580-44f2-11ea-879a-6ac387aee719.png)
![2020-02-01_12 59 45](https://user-images.githubusercontent.com/60527388/73596739-003d9900-44f3-11ea-8e30-2e85b6ab9e72.png)

**Comment by davenonymous** [comment]
You are welcome! I'm working on improving the Bonsai Maker a bit more so others don't run into the issues you did! Thanks for the report!
