### ISSUE TITLE
crashes client on initialization

### ISSUE THREAD

**Issue by imilian007** [thraaawn/BonsaiTrees#146]
see log:

[crash-2020-02-03_11.11.35-client.txt](https://github.com/thraaawn/libnonymous/files/4149170/crash-2020-02-03_11.11.35-client.txt)

**Comment by davenonymous** [comment]
This is a Bonsai Trees issue, so I've moved it from libnonymous over here.
Since I am unable to reproduce this, would you mind retesting it with the latest build 2.1.2.7 from [here](https://github.com/thraaawn/BonsaiTrees/packages/95904)? Thanks!

**Comment by DeanR97** [comment]
I have the same Issue if i use this Mod in combination with dank storage.

**Comment by Seikikai** [comment]
Getting Same Error With 1.14.4 Version

https://paste.link/p2/2APsDSBWn2WWWkFroxOhJQ.txt

**Comment by stevojhall** [comment]
i was getting the original error that was reported with 2.1.2.6 and am now getting this error https://pastebin.com/jHjq2FRd with 2.1.2.7

**Comment by stevojhall** [comment]
oh and this is not just with dankstorage as i removed dankstorage and was still getting this with an edited version of all the mods 5

EDIT: https://www.curseforge.com/minecraft/mc-mods/better-bedrock-generator is also causing this (at least from adding 1 mod at a time)

**Comment by davenonymous** [comment]
Thanks for the report on the 2.1.2.7 build.
I will need to investigate further.

**Comment by davenonymous** [comment]
This is apparently a [known issue in forge](https://github.com/MinecraftForge/MinecraftForge/issues/5862).
Could you pastebin the full latest.log file for the crash?

**Comment by Shindur** [comment]
@thraaawn To help ya with this I'm going to put my latest.log file here. It's for a custom pack I'm making for 1.15.2, but it crashes with the same reasoning as imilian. 
https://pastebin.com/r7UkE2wJ

**Comment by davenonymous** [comment]
Thanks @Shindur, your actual problem is the one right at the top of the log:

> [11:46:20] [modloading-worker-14/ERROR]: Failed to create mod instance. ModID: dankstorage, class tfar.dankstorage.DankStorage
> java.lang.IllegalStateException: install mixin
>     at tfar.dankstorage.DankStorage.<init>(DankStorage.java:53) ~[?:2.5]

This should be reported to DankStorage instead. Actually. It has been: [here](https://github.com/Tfarcenim/Dank-Storage/issues/36).

**Comment by Shindur** [comment]
Gotcha, Thanks @thraaawn. I'll reference that post and see what I need to do as disabling dank storage made MC load up just fine.

**Comment by stevojhall** [comment]
sorry been working and didn't get a chance to check for updates (12+ hour shifts) ill check now (updated pack so will check if i'm still getting error although can't see why i wouldn't)

EDIT: 2.1.2.6 latest.log https://pastebin.com/TMMXSE9Q
2.1.2.7 latest.log https://pastebin.com/4DZgTu6y

**Comment by davenonymous** [comment]
You are having the same problem as shindur.
```
[21:11:58] [modloading-worker-0/ERROR]: Failed to create mod instance. ModID: dankstorage, class tfar.dankstorage.DankStorage
java.lang.IllegalStateException: install mixin
```

**Comment by stevojhall** [comment]
so dankstorage failing to create a mod instance is what is causing bonsai trees to crash?

**Comment by davenonymous** [comment]
[DankStorage depends on mixin.](https://github.com/Tfarcenim/Dank-Storage/issues/36#issuecomment-576050793)

**Comment by Knito58** [comment]
What is it in my case then? No DankStorage here.
https://pastebin.com/ndUS3Sb2
I would happily try to uninstall it. Never will uninstall BT.

**Comment by davenonymous** [comment]
Attach the full latest.log, not the shortened crash log to see the actual error.

**Comment by RViper80** [comment]
Just tried creating a 1.15.2 game using the Forager modpack.  Got this crash also.

[Full log](https://pastebin.com/g7rsVqbp)

**Comment by davenonymous** [comment]
> Just tried creating a 1.15.2 game using the Forager modpack. Got this crash also.
```
[14Feb2020 13:34:51.042] [modloading-worker-4/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: refinedstorage, class com.raoulvdberge.refinedstorage.RS
java.lang.ExceptionInInitializerError: null
```
Report this to Refined Storage.

**Comment by Knito58** [comment]
What is it in my case then? No DankStorage here.
https://pastebin.com/ndUS3Sb2

Edit: OK it was Refined Storage.
