### ISSUE TITLE
1.15.2 Added ferroustry vanilla resource trees

### ISSUE THREAD

**Issue by Knito58** [thraaawn/BonsaiTrees#147]
... but derped when trying to make a pull request from it. Atm I have done the models and recipes fort the 7 vanilla trees (iron, gold, quartz, emerald, diamond, lapis and redstone).
Works nicely in my local world.
Help needed.

**Comment by davenonymous** [comment]
This is the shortest I can explain this without writing a full tutorial on it:

If you know how git works you can do it properly using e.g. [this tutorial](https://opensource.com/article/19/7/create-pull-request-github). There are many more available a quick google search away.

If you don't know how git works you can just treat github as a dropbox kind of thing and do everything via the webinterface: Fork the repo (you've done that already), browse to the appropriate folders and press the upload files button. Each upload needs to have a "commit message" that makes sense. Once you've uploaded all files to the correct places and with the correct folder and filenames you go back to the main page of your repository and click the "Create Pull Request" button.

**Comment by kreezxil** [comment]
I was fixing to ask about support for ferroustry. Now I'm hoping @Knito58 can figure out how to do his PR or at least drop the changes here for you to implement.

:)

**Comment by Knito58** [comment]
Ah I see where I did st wrong: I first cloned the project to my github account - unwillingly. Then tried to delete it. Failed. Totaly frustrated cloned your original to my desktop, applied the changes and the commit told me that this ist the same fork and na na na.
Hold your breath. I'm doing that tuto. That cannot be that hard.

**Comment by Knito58** [comment]
My very first pull request is up after years of using github only for nagging you guys.
Thanks for your patience and help!
Bonsai Trees + Ferroustry = Bestest resource farm ever.

**Comment by Knito58** [comment]
... and today the Githup Repos do show the changes.
Its not an issue anymore. These days I will see to make a copper sapling and then the rest of the modded trees to support Ferroustry totally.
