### ISSUE TITLE
Grow Speed Tick

### ISSUE THREAD

**Issue by zodiak246** [thraaawn/BonsaiTrees#149]
I am trying to make it so the tree grows after 45 mins, but the speed isn't changing for some reason. 
I'm using a tick calculator and inputting the numbers, but it doesn't seem to work
http://mapmaking.fr/tick/

**Comment by davenonymous** [comment]
**Please provide some information.**
"It's not working" is nothing. I don't care how you came up with 45 * 60 * 20. Provide useful information please. New tree? Existing tree? Minecraft version? Bonsai version? Where did you enter the new grow time?

**Comment by zodiak246** [comment]
I am making a bonsai version for ferrostry 
![image](https://user-images.githubusercontent.com/60527388/74362246-5c77a700-4d96-11ea-8d01-8341fbc273e5.png)
 this is where I input the growth speed, 36000 ticks= 30 mins. 

This is what i've made and copied to the bonsai tree mod. 
[openloader.zip](https://github.com/thraaawn/BonsaiTrees/files/4193981/openloader.zip)
*Note* I do not have openloader installed. 
Playing on version 1.15.2
