### ISSUE TITLE
Stopping tree growth animation when connected inventory is full

### ISSUE THREAD

**Issue by it-is-I-Pants** [thraaawn/BonsaiTrees#15]
Title says it all, really. It'd be a nice touch to stop the tree growth animation in the hopping bonsai pot when the inventory below it is full and then starting it when there's space again.

**Comment by thraaawn** [comment]
I do not understand. That's exactly how it currently behaves.
Progress of tree growth is only reset to 0 if the Hopping Bonsai Pot was able to insert one of the drops into the inventory below.

How did you test this?

**Comment by it-is-I-Pants** [comment]
I've tested this with crates from immersive engineering and storage drawers. I'll do some more testing and get back to you
