### ISSUE TITLE
[Enhancement] Compatibility with Ferroustry

### ISSUE THREAD

**Issue by FuuNoKamiOka** [thraaawn/BonsaiTrees#150]
It's a mod that has trees that give you wood based on different metals and ores. Tries using a Lead one in it and it won't work.

**Comment by Yamza** [comment]
Would like to add to this:
https://www.curseforge.com/minecraft/mc-mods/forbidden-arcanus
https://www.curseforge.com/minecraft/mc-mods/good-nights-sleep

**Comment by Kizwiz** [comment]
Thissssssssssssssssssss! Please do this devs

**Comment by LlubNek** [comment]
see here (https://github.com/thraaawn/BonsaiTrees/issues/178) for 1.15.2 or here (https://github.com/thraaawn/BonsaiTrees/issues/22#issue-283669873) for 1.12.2.
