### ISSUE TITLE
FPS Droping when looking at bonsai pot 

### ISSUE THREAD

**Issue by UnRealDinnerbone** [thraaawn/BonsaiTrees#160]
Mod Version: 2.1.2.6
Forge Version: 1.15.2-31.1.18

There is a very noticeable FPS drop when looking a bonsai pot 

Not looking on pot: https://unreal.codes/2020/3/9/1583797406878-javaw_6vwjGVaBtq.png
Looking at one pot: https://unreal.codes/2020/3/9/1583797433414-javaw_WG4UZrYF12.png
Looking at muti pots: https://unreal.codes/2020/3/9/1583797468430-javaw_DlXROQXRVM.png

**Comment by davenonymous** [comment]
Jupp. No more DisplayLists in 1.15. Need to investigate how VBOs work and implement that.

**Comment by UnRealDinnerbone** [comment]
Any update on this issue?

**Comment by GamingInfinite** [comment]
Honestly, this could be a possible problem with the way your graphics are being handled by your card.  Still a problem on the mod side as it should be able to handle any card.  I don't have the same problem, but if it's only when looking directly at the growing tree then just hide them behind a wall and use hoppers to transport them through the wall to a chest where it all filters to.
