### ISSUE TITLE
[1.15.2] NullPointerException PotColorizer.init

### ISSUE THREAD

**Issue by YasminEndusa** [thraaawn/BonsaiTrees#161]
Mod Version: 2.1.2.6 (2.1.2.4)  
Forge Version: 1.15.2-31.1.19  

client crash report: https://hastebin.com/dolubefone.rb  
latest.log: https://hastebin.com/xudupeneku.md  

I'm getting the crash when i try to run my custom pack with version 2.1.2.6 (also tried with 2.1.2.4 with the same error).

**Comment by davenonymous** [comment]
Duplicate of #146 
[DankStorage requires Mixin](https://github.com/Tfarcenim/Dank-Storage/issues/36#issuecomment-576050793)
