### ISSUE TITLE
Pam's Harvestcraft 2 Trees Support [1.15.2]

### ISSUE THREAD

**Issue by GamingInfinite** [thraaawn/BonsaiTrees#172]
I don't know whether this is supposed to go to you, or to Pam as the mod author, but could you add support for the trees she's adding?  It would add a whole new level of automation for the things I want to do in my world.

**Comment by LlubNek** [comment]
MasterSloth1 posted Pam's support for 1.15.2 here:  https://github.com/thraaawn/BonsaiTrees/issues/178#issue-604901892
