### ISSUE TITLE
[1.15] more compatability

### ISSUE THREAD

**Issue by MasterSloth1** [thraaawn/BonsaiTrees#178]
[ForbiddenArcana-Data.zip](https://github.com/thraaawn/BonsaiTrees/files/5077918/ForbiddenArcana-Data.zip)
[ForbiddenArcana-Resources.zip](https://github.com/thraaawn/BonsaiTrees/files/5077919/ForbiddenArcana-Resources.zip)
[Midnight-Data.zip](https://github.com/thraaawn/BonsaiTrees/files/5077920/Midnight-Data.zip)
[Midnight-Resources.zip](https://github.com/thraaawn/BonsaiTrees/files/5077921/Midnight-Resources.zip)
[Mubble-Data.zip](https://github.com/thraaawn/BonsaiTrees/files/5077922/Mubble-Data.zip)
[Mubble-Resources.zip](https://github.com/thraaawn/BonsaiTrees/files/5077923/Mubble-Resources.zip)
[Pamshc2Trees-Data.zip](https://github.com/thraaawn/BonsaiTrees/files/5077924/Pamshc2Trees-Data.zip)
[Pamshc2Trees-Resources.zip](https://github.com/thraaawn/BonsaiTrees/files/5077925/Pamshc2Trees-Resources.zip)

**Comment by LlubNek** [comment]
here's mine:
[upgradeaquaticbonsais_resources.zip](https://github.com/thraaawn/BonsaiTrees/files/4906734/upgradeaquaticbonsais_resources.zip)
[ferroustrybonsais_resources.zip](https://github.com/thraaawn/BonsaiTrees/files/4906735/ferroustrybonsais_resources.zip)
[forbiddenarcanusbonsais_resources.zip](https://github.com/thraaawn/BonsaiTrees/files/4906736/forbiddenarcanusbonsais_resources.zip)
[upgradeaquaticbonsais_data.zip](https://github.com/thraaawn/BonsaiTrees/files/4906737/upgradeaquaticbonsais_data.zip)
[ferroustrybonsais_data.zip](https://github.com/thraaawn/BonsaiTrees/files/4906738/ferroustrybonsais_data.zip)
[forbiddenarcanusbonsais_data.zip](https://github.com/thraaawn/BonsaiTrees/files/4906739/forbiddenarcanusbonsais_data.zip)

**Comment by grandogarndo** [comment]
Quick question, how exactly do I install these resources?

**Comment by MasterSloth1** [comment]
1 you can make a data pack and resource pack and use them that way 
2 you can install openloader mod and load them that way :D

**Comment by LlubNek** [comment]
For mine, once you have openloader you can drop the zip files into the openloader/data and openloader/resources folders as appropriate.  You should also be able to use them without openloader if you know how datapacks work.  MasterSloth1's will take a bit more work to do properly (separate data and resources, rename the custombonsais folders to be somewhat unique, and fix the pack.mcmeta files), but you can just extract them all into the openloader folder and it should work.

**Comment by grandogarndo** [comment]
Thanks so much you guys are geniuses

**Comment by grandogarndo** [comment]
actually quick question: I watched a YouTuber play valhesia 2 and it seemed like he could plant whatever tree he wanted. do you know where those resources came from? (obviously pack makers have secrets, and maybe they didn't do anything)

**Comment by grandogarndo** [comment]
Master sloth's ZIPs say that they have nothing in them and are invalid. is that supposed to happen?

**Comment by MasterSloth1** [comment]
sounds like u have corrupt zip files when i download them they work fine, or you unzipped the folder incorrectly im not sure how your trying to load the files

**Comment by grandogarndo** [comment]
yeah i think they are corrupt, can i fix that?

**Comment by MasterSloth1** [comment]
redownload the files lol

**Comment by grandogarndo** [comment]
i re downloaded and it says the files are empty

**Comment by grandogarndo** [comment]
![image](https://user-images.githubusercontent.com/56941237/90300154-4347d400-de67-11ea-8594-575a2f533ee8.png)

**Comment by MasterSloth1** [comment]
yea idk open it with 7zip and it works ill remake the zip files like how  LlubNek done theirs

**Comment by MasterSloth1** [comment]
[ForbiddenArcana-Data.zip](https://github.com/thraaawn/BonsaiTrees/files/5077918/ForbiddenArcana-Data.zip)
[ForbiddenArcana-Resources.zip](https://github.com/thraaawn/BonsaiTrees/files/5077919/ForbiddenArcana-Resources.zip)
[Midnight-Data.zip](https://github.com/thraaawn/BonsaiTrees/files/5077920/Midnight-Data.zip)
[Midnight-Resources.zip](https://github.com/thraaawn/BonsaiTrees/files/5077921/Midnight-Resources.zip)
[Mubble-Data.zip](https://github.com/thraaawn/BonsaiTrees/files/5077922/Mubble-Data.zip)
[Mubble-Resources.zip](https://github.com/thraaawn/BonsaiTrees/files/5077923/Mubble-Resources.zip)
[Pamshc2Trees-Data.zip](https://github.com/thraaawn/BonsaiTrees/files/5077924/Pamshc2Trees-Data.zip)
[Pamshc2Trees-Resources.zip](https://github.com/thraaawn/BonsaiTrees/files/5077925/Pamshc2Trees-Resources.zip)

**Comment by MasterSloth1** [comment]
[ExplorerCraft-Data.zip](https://github.com/thraaawn/BonsaiTrees/files/5080476/ExplorerCraft-Data.zip)
[ExplorerCraft-Resources.zip](https://github.com/thraaawn/BonsaiTrees/files/5080477/ExplorerCraft-Resources.zip)
[SilentGear-Data.zip](https://github.com/thraaawn/BonsaiTrees/files/5080478/SilentGear-Data.zip)
[SilentGear-Resources.zip](https://github.com/thraaawn/BonsaiTrees/files/5080479/SilentGear-Resources.zip)
