### ISSUE TITLE
[Suggestion] The Betweenlands and Fossils and Archeology Revivals

### ISSUE THREAD

**Issue by BriceFable** [thraaawn/BonsaiTrees#181]
These are two rather big mods, that I'd love to see compatibility with added in 1.12.2 eventually.
I would do it on my own but I don't know much about minecraft modding.

https://www.curseforge.com/minecraft/mc-mods/fossils
https://www.curseforge.com/minecraft/mc-mods/angry-pixel-the-betweenlands-mod

**Comment by ArkenorOakshadow** [comment]
Worth noting that Betweenlands also has a block called Slimy Grass, so it should probably be looked at anyway.
