### ISSUE TITLE
Bonsai Tree 2 vs JEI

### ISSUE THREAD

**Issue by Rogrom73** [thraaawn/BonsaiTrees#184]
I just installed mod Bonsai Tree 2 and discovered that it was interfering with JEI. MC don't crash but it is impossible to open JEI interface. No idea if it is a JEI or Bonsai Tree issue or combination with other parameters as I have lot of other mods installed. I am using MC 1.15.2 with Forge 31.1.77 and last version of the 2 mods.

**Comment by whatthedrunk** [comment]
We have been having this issue with ATM5 as well. Players have to login to a single player world and then back into the server for JEI to load. 
https://github.com/AllTheMods/ATM-5/issues/86
