### ISSUE TITLE
visual issue with hopping bonsai pot

### ISSUE THREAD

**Issue by Debje** [thraaawn/BonsaiTrees#185]
The normal bonsai pot works normally but the hopping pot doesn't show animations.

Minecraft 1.15.2
Forge 1.15.2-31.1.0
bonsaitrees-2.1.0.1
![2020-05-10_22 23 00](https://user-images.githubusercontent.com/65134562/81509907-4aae8d00-930e-11ea-8f8e-cf7ab3055d8c.png)
![2020-05-10_22 26 24](https://user-images.githubusercontent.com/65134562/81509911-4edaaa80-930e-11ea-89fa-13d619be6744.png)

**Comment by Curlz242** [comment]
I have the same Problem.
Running (All the Mods 5) Forge 31.2.0 
MC 1.15.2

Hopper Bonsai show no soil nor tree nor animation.
Normal Bonsai Pots are working fine.

**Comment by davenonymous** [comment]
Sorry, I'm personally not supporting any versions below the upcoming 1.18.1 version.
Maybe someone else wants to pick things up for older versions - I simply don't have the time.
