### ISSUE TITLE
Is there any guide for personalized saplings?

### ISSUE THREAD

**Issue by Superplay360** [thraaawn/BonsaiTrees#186]
Hi, I'm trying to make my personalized saplings/trees in Minecraft with BonsaiTrees. I've read I have to use openloader or CraftTweaker but I don't know how to start and I think many people also don't know that. I have also read about BonsaiTree Maker GUI but I don't know how to use it and I don't want to make something wrong and destroy default saplings.

Is there any guide which explain how to do it? For example, how to get cactus saplings in this wonderful mod?

Thank you very much, Estanis

**Comment by ShockPuppet** [comment]
did you get a result for this question? i also would like to know

**Comment by Shockks** [comment]
> Hi, I'm trying to make my personalized saplings/trees in Minecraft with BonsaiTrees. I've read I have to use openloader or CraftTweaker but I don't know how to start and I think many people also don't know that. I have also read about BonsaiTree Maker GUI but I don't know how to use it and I don't want to make something wrong and destroy default saplings.
> 
> Is there any guide which explain how to do it? For example, how to get cactus saplings in this wonderful mod?
> 
> Thank you very much, Estanis

did you get a result for this question? i also would like to know

**Comment by Superplay360** [comment]
> > Hi, I'm trying to make my personalized saplings/trees in Minecraft with BonsaiTrees. I've read I have to use openloader or CraftTweaker but I don't know how to start and I think many people also don't know that. I have also read about BonsaiTree Maker GUI but I don't know how to use it and I don't want to make something wrong and destroy default saplings.
> > Is there any guide which explain how to do it? For example, how to get cactus saplings in this wonderful mod?
> > Thank you very much, Estanis
> 
> did you get a result for this question? i also would like to know

Ummm, something like that. I was looking for in Google and I found this:
[Link](https://www.reddit.com/r/feedthebeast/comments/ejkk1a/bonsai_trees_on_114_will_have_a_gui_assisted_tree/)

I hope it helps you, although I have to check it yet. You'll need openloader because I've checked it without openloader and it doesn't found.

**Comment by McKitten** [comment]
A wiki page on how to add a datapack for this mod would be awesome; for some reason I can't get the .json & https://www.curseforge.com/minecraft/mc-mods/drp-global-datapack to work / add new varieties and it is frustrating me as there is new biome packs available that need them (BYG in my case).
