### ISSUE TITLE
[1.12] Extreme lag when looking at pots

### ISSUE THREAD

**Issue by melody-rs** [thraaawn/BonsaiTrees#187]
I have an array of bonsai pots in my base, for a skewer farm. Whenever I look in the general direction of the pots, despite them being obscured, my game *lags heavily.*

**Comment by Konicai** [comment]
Minecraft still renders tile entities if they are obscured. 

Personally I used [this](https://github.com/thraaawn/BonsaiTrees/issues/204#issuecomment-693111251) method to stop the trees from rendering. If you want to see them again just remove the entry from the config or disable the StopRender mod before starting minecraft. 

You could also put all bonsais in a compact machine.

**Comment by davenonymous** [comment]
Sorry, I'm personally not supporting any versions below the upcoming 1.18.1 version.
Maybe someone else wants to pick things up for older versions - I simply don't have the time.
