### ISSUE TITLE
missing outputs

### ISSUE THREAD

**Issue by LlubNek** [thraaawn/BonsaiTrees#190]
no leaves for netherwood, no apples for oak or dark oak, no vines or cocoa beans for jungle

using BonsaiTrees-2.1.2.6.jar

**Comment by LlubNek** [comment]
nvm netherwood.  that's added from silent gear's end

**Comment by LlubNek** [comment]
[vanillabonsais_data.zip](https://github.com/thraaawn/BonsaiTrees/files/4906732/vanillabonsais_data.zip)
[silentgearbonsais_data.zip](https://github.com/thraaawn/BonsaiTrees/files/4906733/silentgearbonsais_data.zip)
a fix

**Comment by davenonymous** [comment]
Sorry, I'm personally not supporting any versions below the upcoming 1.18.1 version.
Maybe someone else wants to pick things up for older versions - I simply don't have the time.
