### ISSUE TITLE
Does NBT work with personalized saplings?

### ISSUE THREAD

**Issue by GlitchedChaser** [thraaawn/BonsaiTrees#193]
**Hello!
I was wondering with something with the Bonsai Maker, does the item that you put in to be a sapling can be changed with NBT/Tags, and only the exact same item can be used for planting.

The reason I am asking, Im making a datapack that makes "Ore Saplings" [Well really Oak Saplings with NBT Lore tags saying what sapling it is].
Ill do my own testing my self, just curious if it does**

**Comment by davenonymous** [comment]
Sorry, I'm personally not supporting any versions below the upcoming 1.18.1 version.
Maybe someone else wants to pick things up for older versions - I simply don't have the time.
