### ISSUE TITLE
[1.15.2] 12 seconds of loading on join

### ISSUE THREAD

**Issue by Darkere** [thraaawn/BonsaiTrees#194]
Upon joining a server Bonsai trees seems to spend a total of 12 seconds loading ..recipes?
![image](https://user-images.githubusercontent.com/4283717/87091972-e4c18180-c23a-11ea-8ed5-3b25a57aa5df.png)

[Enigmatica 5 join profiling Snapshot](https://github.com/thraaawn/BonsaiTrees/files/4899589/e5serverjoin.zip)

That seems like a ridiculous amount of time to spent while the player is joining a server. 

BonsaiTrees-2.1.2.6.jar

**Comment by davenonymous** [comment]
Sorry, I'm personally not supporting any versions below the upcoming 1.18.1 version.
Maybe someone else wants to pick things up for older versions - I simply don't have the time.
