### ISSUE TITLE
[1.12.2] Compatability bug with ProjectE's Ring of Arcana in Harvest Mode

### ISSUE THREAD

**Issue by OfficialTomPG** [thraaawn/BonsaiTrees#195]
When using ProjectE's Ring of Arcana in Harvest mode, Hopping Bonsai Pots will disappear at random intervals, despite having soil and a sapling.  They do not drop on the ground as an item, rather just delete themselves from the world.

**Comment by davenonymous** [comment]
Sorry, I'm personally not supporting any versions below the upcoming 1.18.1 version.
Maybe someone else wants to pick things up for older versions - I simply don't have the time.
