### ISSUE TITLE
[Suggestion]+[Question] Adding support for the "Apricorn Tree Farm" mod

### ISSUE THREAD

**Issue by DerShendi** [thraaawn/BonsaiTrees#196]
The title says it all but id also like to ask a question on (if possible) how do i add custom trees (trees from mods that arent supported yet) and some extra soil (like snad to improve Bonsai speed for Sugarcanes)
MC 1.12.2

**Comment by Rogue238** [comment]
If you look in the config files, there is a section for some json files.  There used to be a wiki online talking about how to add them and giving example files, but it has disappeared.  What you can do is look inside the mod itself, find the files (under types.d, shapes.d, and soil.d), look at them, and work it out.  There is a command you can use to save the tree shapes in game and I recommend using it before editing the shape file.  As for adding snad, you would add the soil json (into your config files) and then add a new file for sugarcane adding snad as a valid soil using tags.

**Comment by DerShendi** [comment]
Thanks for the help

**Comment by Rogue238** [comment]
You're welcome.  Sorry it's not a lot.

**Comment by DerShendi** [comment]
nah its ok that was a lot already even i who barely knows enough how to do smth can work it out with that

**Comment by Rogue238** [comment]
Oh good! :)

**Comment by DerShendi** [comment]
ok now i know how to add shapes and such and i started adding some but how do i add them to the game i dont know that part yet
imma be honest its stupid how the wiki got nuked and imma try to make smth on the lines of that just because of how annoyed im from it

**Comment by DerShendi** [comment]
NVM finally found out how everything works and that tutorial that i said its gonna be a f*ckin promise

**Comment by davenonymous** [comment]
Sorry, I'm personally not supporting any versions below the upcoming 1.18.1 version.
Maybe someone else wants to pick things up for older versions - I simply don't have the time.
