### ISSUE TITLE
[Question] [1.12.2] 3D Objects in the Bonsai Pots

### ISSUE THREAD

**Issue by TheNicklao** [thraaawn/BonsaiTrees#197]
Hello. I am currently trying to add Apricorns from the Pixelmon mod to the Bonsai list, and have gotten them growing. I have however run into a bit of a issue as it would appear the Pixelmon mod's Apricorn trees as well as Berry bushes use 3D objects for the model instead of blocks with textures layered over that minecraft seems to use normally. Is there something special I have to add to either the shape file or the type file to make it load the model properly, or is this simply not doable with the way the Bonsai pot handles the models?
For clarification in case it matters, when I say the models are 3D Objects, I mean that that are in .obj format.

Attached is a picture showcasing the Apricorn tree as it appears ingame. Bonsai pot for scale
![2020-07-14_19 55 29](https://user-images.githubusercontent.com/32207092/87459754-1a37e780-c60c-11ea-889e-9e3e7a83d2d5.png)

**Comment by davenonymous** [comment]
Not doable, sorry.
