### ISSUE TITLE
[Suggestion] Add support for tree drops from VanillaFoodPantry

### ISSUE THREAD

**Issue by whiteeagle1985** [thraaawn/BonsaiTrees#199]
Hi,

I would like to see if Vanilla Food Pantry is installed beside Bonsai Trees, that oak bonsais also drop acorns and jungle trees also drop raftugli fruit. It could be a small percentage, but I'd love to see this done cause I love both mods.

The version I play is for 1.12.2 - thanks.

**Comment by davenonymous** [comment]
Sorry, I'm personally not supporting any versions below the upcoming 1.18.1 version.
Maybe someone else wants to pick things up for older versions - I simply don't have the time.
