### ISSUE TITLE
bonsai pots not compatible with ferroustry saplings [1.15.2]

### ISSUE THREAD

**Issue by Robomnz** [thraaawn/BonsaiTrees#201]
https://www.curseforge.com/minecraft/mc-mods/ferroustry

none of the saplings in the mod linked above for 1.15.2 are compatible with bonsai pots is it possible that you could make these saplings in the ferroustry mod compatible with bonsai pots?

**Comment by LlubNek** [comment]
I posted data and resource packs for Ferroustry on 1.15.2 here: https://github.com/thraaawn/BonsaiTrees/issues/178#issuecomment-657055045

**Comment by davenonymous** [comment]
Sorry, I'm personally not supporting any versions below the upcoming 1.18.1 version.
Maybe someone else wants to pick things up for older versions - I simply don't have the time.
