### ISSUE TITLE
[1.15.2] Fatal Error?

### ISSUE THREAD

**Issue by Yourname942** [thraaawn/BonsaiTrees#205]
Latest Log: https://gist.github.com/Yourname942/c221044542cea6cebe8cda9434b8435b
Crash Log: https://gist.github.com/Yourname942/d3bc45fa46c3a331352f9e34f2524375

Minecraft: 1.15.2
Forge: 31.2.36
BonsaiTrees: 2.1.2.6

Launch Twitch App
Click Play (purple button in Twitch App)
Click Play (green button in Minecraft Launcher)
Crash occurs while Forge is loading mods (I think)

**Comment by davenonymous** [comment]
Sorry, I'm personally not supporting any versions below the upcoming 1.18.1 version.
Maybe someone else wants to pick things up for older versions - I simply don't have the time.
