### ISSUE TITLE
Conflict with Simple Farming mod

### ISSUE THREAD

**Issue by Areolata7** [thraaawn/BonsaiTrees#206]
Tried to run BonsaiTrees-2.0.2.35.jar with 1.14.4 and forge 28.2.0 and Simple Farming 1.2.1

Forge will not load Bonsai Trees for the following reason:
"The property waterlogged is not valid for block simplefarming:fruit_log"

I really only care about vanilla trees so I would happily put all of the simple farming blocks on a black list for bonsai trees. However I see no such option in the config files. 

Any suggestions?

**Comment by davenonymous** [comment]
Sorry, I'm personally not supporting any versions below the upcoming 1.18.1 version.
Maybe someone else wants to pick things up for older versions - I simply don't have the time.
