### ISSUE TITLE
Silent Gear's netherwood tree model doesn't render

### ISSUE THREAD

**Issue by noamsm** [thraaawn/BonsaiTrees#208]
### Description
Silent Gear's netherwood tree is supported as a valid bonsai tree but is not displaying a model in the pot.
![2020-08-18_15 50 19](https://user-images.githubusercontent.com/19357208/90515331-2c58f880-e16b-11ea-9d73-9679a7f509a1.png)

### Versions
Minecraft: 1.15.2
Forge: 31.2.36
Bonsai Trees 2: 2.1.2.6
Silent Gear: 1.11.3+160

**Comment by davenonymous** [comment]
Sorry, I'm personally not supporting any versions below the upcoming 1.18.1 version.
Maybe someone else wants to pick things up for older versions - I simply don't have the time.
