### ISSUE TITLE
Bonsai Trees Not Rendering And Showing "NaN%"

### ISSUE THREAD

**Issue by NialMontana** [thraaawn/BonsaiTrees#209]
I've been experiencing an issue with both hopping and standard pots where the tree does not render at all and the percentage on WAILA shows NaN%. The pots functionally are working but are simply not rendering. Any advice or help would be appreciated.

**Comment by davenonymous** [comment]
Sorry, I'm personally not supporting any versions below the upcoming 1.18.1 version.
Maybe someone else wants to pick things up for older versions - I simply don't have the time.
