### ISSUE TITLE
Could you make Cactus and Sugarcane work with the pots?

### ISSUE THREAD

**Issue by Dragnier** [thraaawn/BonsaiTrees#21]
Or make another pot type for them if they are incompatible with the current setup? I think it would be cool and useful specifically for these two plants.

**Comment by thraaawn** [comment]
Sorry, these are not trees. IE's garden cloches work quite well for them.

You can add them yourself to the packs you are playing by creating appropriate .json configs. See the readme for more details on how to do that.

**Comment by Dragnier** [comment]
Eh, I was honestly just hoping for a new, cool looking way to decorate with them. Sort of like the planters you see in restaurants with Bamboo and whatnot. But, I understand. 😄 

Also, not everyone uses IE or any mod that performs a similar function in every pack they play... I'll take a look at the custom configs. I didn't know if they'd work with cactus and sugarcane.
