### ISSUE TITLE
How to disable a sapling in the config.

### ISSUE THREAD

**Issue by LotusRayne** [thraaawn/BonsaiTrees#211]
Hello, i have tired many different times and ways to disable a sapling from the mob, Forbidden & Arcanenus . The sapling in question is the is the Mysterywood sapling  and no matter what i try it wont disable where you cant put it into a bonsai pot. The reason i am trying to disable this for me and my friends is becase i dont want a automatic farming way of getting golden apples.

thank you for your time.

**Comment by Konicai** [comment]
Which version of BonsaiTrees are you using?

**Comment by LotusRayne** [comment]
I believe it is the latest 1.12.2 version

**Comment by Konicai** [comment]
You have two options. You can either disable the use of the tree as a bonsai by editing the bonsaitrees settings.cfg as such

    # Tree types to disable (e.g. forestry:hillCherry) [default: ]
    S:disabledTreeTypes <
	forbidden_arcanus:mysterywood
     >

Or you can solely disable the golden apple drop by putting this json in the types.d folder of the bonsaitrees config folder. 
[forbidden_arcanus_mysterywood-NoGapple.zip](https://github.com/thraaawn/BonsaiTrees/files/5242922/forbidden_arcanus_mysterywood-NoGapple.zip)

Make sure to do this in the server configuration. If you join the server without the config changes you'll still be able to see the normal recipe in JEI, but it doesn't actually affect your ability on the server.
