### ISSUE TITLE
I'm going to add byg compatibility, i will post it when i get it done

### ISSUE THREAD

**Issue by grandogarndo** [thraaawn/BonsaiTrees#213]
If this isn't allowed just delete this i guess

**Comment by grandogarndo** [comment]
[BYG-Resources.zip](https://github.com/thraaawn/BonsaiTrees/files/5294070/BYG-Resources.zip)
[BYG-Data.zip](https://github.com/thraaawn/BonsaiTrees/files/5294071/BYG-Data.zip)

**Comment by davenonymous** [comment]
Sorry, I'm personally not supporting any versions below the upcoming 1.18.1 version.
Maybe someone else wants to pick things up for older versions - I simply don't have the time.
