### ISSUE TITLE
[1.12.2] Not Rendering and Adding Apple Drops

### ISSUE THREAD

**Issue by ClaudiusMinimus** [thraaawn/BonsaiTrees#216]
Minecraft: 1.12.2
Forge: 14.23.5.2854
Bonsai: 1.1.4-b170

I made the following cr_oak.json file to add support for Conquest Reforged oak trees (shown below). Using The One Probe, I can see the sapling growth bar and drops log, sticks, leaves, and saplings as expected.

The issue: are: 

1. The tree growth does not render for this sapling, though it works fine for the Minecraft sapling.
2. Would like to add apples, but I'm not sure what the "type" attribute should be.

I will add other saplings once this issue is fixed and would be happy to provide the files to the community.

> {
>     "name": "minecraft:oak",
>     "mod": "conquest",
>     "sapling": {
>         "name": "conquest:sapling_3",
>         "data": 0
>     },
>     "growTimeMultiplier": 1.0,
>     "drops": [
>         {
>             "name": "minecraft:stick",
>             "data": 0,
>             "type": "STICK"
>         },
>         {
>             "name": "minecraft:log",
>             "data": 0,
>             "type": "WOOD"
>         },
>         {
>             "name": "minecraft:sapling",
>             "data": 0,
>             "type": "SAPLING"
>         },
>         {
>             "name": "minecraft:leaves",
>             "data": 0,
>             "type": "LEAVES"
>         }
>     ]
> }

**Comment by ClaudiusMinimus** [comment]
I've restarted the games a few times and now it is rendering. 
**So the only issue now is how to have apple drops.**

**Comment by ClaudiusMinimus** [comment]
I just tested the default Minecraft oak sapling `minecraft:sapling` and the Bonsai pot will not accept it. I tried changing the name at the top of the script to `conquest:oak` and restarted the game and the default sapling still did not work. Does Minecraft cache recipes? Because it seems with the name change the default sapling should work.

**Comment by Rogue238** [comment]
Change the first name in this:

{
**"name": "minecraft:oak"**,
"mod": "conquest",
"sapling": {
"name": "conquest:sapling_3",
"data": 0
}

It is causing a conflict.  The bonsai pot doesn't know whether to plant a Minecraft Oak Tree or a Conquest Oak Tree because it matches two files (the original oak tree and the new file you created).

**Comment by ClaudiusMinimus** [comment]
I had changed it to:

{
**"name": "conquest:oak",**
"mod": "conquest",
"sapling": {
"name": "conquest:sapling_3",
"data": 0
}

**Comment by Rogue238** [comment]
And then make sure you change the name to match it in the shape files and you should be good.

**Comment by davenonymous** [comment]
Sorry, I'm personally not supporting any versions below the upcoming 1.18.1 version.
Maybe someone else wants to pick things up for older versions - I simply don't have the time.
