### ISSUE TITLE
Apples don't drop in 1.15/1.14, unlike 1.12.2

### ISSUE THREAD

**Issue by BetaCarotina** [thraaawn/BonsaiTrees#217]
Apples don't drop from Oak and Dark Oak trees in Bonsais, and there isn't enough leaves to actually be used for Apples, making their obtainability using the mod's blocks unreasonably hard. I think this feature should be readded, though cocoa beans may still be left without a Bonsai recipe.

**Comment by davenonymous** [comment]
Sorry, I'm personally not supporting any versions below the upcoming 1.18.1 version. And I will probably not add Apple drops back in. Sorry.
Maybe someone else wants to pick things up for older versions - I simply don't have the time.
