### ISSUE TITLE
[1.12.2] [Request] More Trees for Bonsai

### ISSUE THREAD

**Issue by Skaphegor** [thraaawn/BonsaiTrees#22]
I'm hijacking this issue to summarize all requested/fulfilled mods:

- [x] [Natura](https://minecraft.curseforge.com/projects/natura)
- [ ] [Plants](https://minecraft.curseforge.com/projects/plants)
- [ ] [NetherEx](https://minecraft.curseforge.com/projects/netherex)
- [x] [Abyssalcraft](https://minecraft.curseforge.com/projects/abyssalcraft)
- [x] [The Twilight Forest](https://minecraft.curseforge.com/projects/the-twilight-forest)
- [ ] [EvilCraft](https://minecraft.curseforge.com/projects/evilcraft)
- [x] [Terraqueous](https://minecraft.curseforge.com/projects/terraqueous)
- [ ] [Erebus](https://minecraft.curseforge.com/projects/the-erebus)
- [ ] [The Betweenlands](https://minecraft.curseforge.com/projects/angry-pixel-the-betweenlands-mod)
- [x] [Biomes O' Plenty](https://minecraft.curseforge.com/projects/biomes-o-plenty)
- [x] [Thaumcraft](https://minecraft.curseforge.com/projects/thaumcraft)
- [ ] [Wizardry](https://minecraft.curseforge.com/projects/wizardry-mod)
- [x] [Tropicraft](https://minecraft.curseforge.com/projects/tropicraft)

**Comment by Sunconure11** [comment]
Hm, can we suggest trees via this?

Erebus, Terraqueous, and The Betweenlands could all benefit from this.

**Comment by winsrp** [comment]
Is Biomes o Plenty included here?...

**Comment by Sunconure11** [comment]
Wizardry

Thaumcraft (It will be out on 1.12.2 for the general public very soon)

**Comment by hron84** [comment]
AFAIK twilight trees are supported.

**Comment by Sunconure11** [comment]
Tropicraft could be added too

**Comment by WhisperFire26** [comment]
Can you add Thamucraft trees to this request list? That would be greatly appreciated, thank you.

**Comment by hron84** [comment]
@WhisperFire26 see #40

**Comment by samtrion** [comment]
Traverse - https://minecraft.curseforge.com/projects/traverse

**Comment by Xemnes-Keyethkateth** [comment]
I have made the .json file for Random Things spectre trees however I can't seem to get the shapes to work for it

I'll upload the .json here if someone is able to get it to fully work that would be great
[randomthings_spectre.zip](https://github.com/thraaawn/BonsaiTrees/files/2218949/randomthings_spectre.zip)

**Comment by Xemnes-Keyethkateth** [comment]
Hey, I've added the spectre trees from random things but i have no clue how to do a pull request.

I will upload it here for for now, if there is another way to submit it for the mod let me know and I will do so.

[Random things spectre trees.zip](https://github.com/thraaawn/BonsaiTrees/files/2219105/Random.things.spectre.trees.zip)

**Comment by zzzqh** [comment]
Is that mean compatibility for Terraqueous have completed? But in present version I still need to add the trees by myself

**Comment by Eogen** [comment]
Sorry to jump onto bandwagon here, but Terraqueous, while listed in the supported mod list, does not seem to be on by default.  Before I started doing them myself, is there something I am missing?

And on the suggestion list,  EnderLilly and RedOrchid from Extrautils would be nice, if slightly off-theme.

**Comment by thraaawn** [comment]
The version including Terraqueous support is not yet released. There are some major changes in the mod that required more testing than usual.

I'll upload a new release to curseforge soon.

**Comment by MokahTGS** [comment]
As far as I've seen, Natura Trees from the Nether don't work in the pots.  I like the idea of adding support for them using netherack as the soil.

**Comment by Eogen** [comment]
I have loaded the shapes and types files into the current version, and the Terraqueous trees are working fine with (afaik) the existing release.  

@thraaawn -- thanks for all that you do.

**Comment by thraaawn** [comment]
@drakray, @MokahTGS, that's why netherrack is [already integrated](https://github.com/thraaawn/BonsaiTrees/blob/master/src/main/resources/assets/bonsaitrees/config/soils.d/netherrack.json) as a valid soil type.
Would one of you like to try creating the type and shape files for the trees you'd like supported and create a pull request here?

**Comment by BrisingrAerowing** [comment]
I'm in the process of creating compat files for Plants2, Douglas Forest, and Novam Teram. I have Plants2 and Douglas Forest type files completed, and I'm working on the many Novam Teram saplings (which is going to take a bit as they use mostly vanilla blocks, so I have to grow them to see what blocks they use). I'll do a PR with those when I've finished them and generated the shape files.

**Comment by BrisingrAerowing** [comment]
Well, I got the type files created, but the mod will only generate shapes for the first two in the directory.

**Comment by eikotehmouse** [comment]
What's the ETA on adding Plants Mod saplings and NetherEx?

**Comment by ArnicaxRoss** [comment]
Hi. Would it be possible to request Maiden's Marvelous Materials to the bonsai list for future updates, please? And the trees from Floricraft?

**Comment by Kashechum** [comment]
Would Pixelmon Apricorns be an option? I'm sure anyone that plays with that mod would love a good way to automate them.

**Comment by xGarionx** [comment]
Betweenlands would be a nice additions ( i tried make the bonsai json/textures today but they dont seem to like each other all to much)

**Comment by MasterSloth1** [comment]
[Plants 2.zip](https://github.com/thraaawn/BonsaiTrees/files/3131702/Plants.2.zip)
[The Between lands.zip](https://github.com/thraaawn/BonsaiTrees/files/3132124/The.Between.lands.zip)
hope these 2 are up to your standards 😄 

either im blind or there is no saplings for netherEx
wizardry sapling you couldnt get naturally so i never done it if u can get it i dont mind adding it

**Comment by Rogue238** [comment]
This is probably one of my very favorite mods.  I've added quite a few trees, but like Xemnes-Keyethkateth, I have no idea how to do a pull request.  I've tried, but I'm new to GitHub.  I have tested all of them and they did work.  So, here is my contribution and I hope someone finds this useful:

[bonsaitrees-chinjufumod.zip](https://github.com/thraaawn/BonsaiTrees/files/3511989/bonsaitrees-chinjufumod.zip)
[bonsaitrees-fossil.zip](https://github.com/thraaawn/BonsaiTrees/files/3511992/bonsaitrees-fossil.zip)
[bonsaitrees-quark.zip](https://github.com/thraaawn/BonsaiTrees/files/3511994/bonsaitrees-quark.zip)
[bonsaitrees-PamsRedbud.zip](https://github.com/thraaawn/BonsaiTrees/files/3511995/bonsaitrees-PamsRedbud.zip)
[bonsaitrees-PamsSpooky.zip](https://github.com/thraaawn/BonsaiTrees/files/3511997/bonsaitrees-PamsSpooky.zip)
[bonsaitrees-StygianEnd.zip](https://github.com/thraaawn/BonsaiTrees/files/3511999/bonsaitrees-StygianEnd.zip)
[bonsaitrees-Zoestria.zip](https://github.com/thraaawn/BonsaiTrees/files/3512001/bonsaitrees-Zoestria.zip)
[bonsaitrees-afraidofthedark.zip](https://github.com/thraaawn/BonsaiTrees/files/3512005/bonsaitrees-afraidofthedark.zip)
[bonsaitrees-defiled.zip](https://github.com/thraaawn/BonsaiTrees/files/3512007/bonsaitrees-defiled.zip)
[bonsaitrees-evilcraft.zip](https://github.com/thraaawn/BonsaiTrees/files/3512012/bonsaitrees-evilcraft.zip)
[bonsaitrees-Midnight.zip](https://github.com/thraaawn/BonsaiTrees/files/3512015/bonsaitrees-Midnight.zip)
[bonsaitrees-spookybiomes.zip](https://github.com/thraaawn/BonsaiTrees/files/3512016/bonsaitrees-spookybiomes.zip)
[bonsaitrees-TolkienTweaksMobs.zip](https://github.com/thraaawn/BonsaiTrees/files/3512018/bonsaitrees-TolkienTweaksMobs.zip)
[bonsaitrees-Aether.zip](https://github.com/thraaawn/BonsaiTrees/files/3512122/bonsaitrees-Aether.zip)
[bonsaitrees-erebus.zip](https://github.com/thraaawn/BonsaiTrees/files/3512123/bonsaitrees-erebus.zip)

**Comment by Imrald** [comment]
What about adding to the list mods like Project Vibrant Journey by solis_nova123 and WildNature by matez?
I'm not able to do it myself but maybe there's someone else who is interested in and has the capability to.
Have a nice day everyone!

**Comment by LlubNek** [comment]
I added shapes and types for the following trees:
forbidden_arcanus:cherrywood
forbidden_arcanus:mysterywood
evilcraft:undead
extrautils2:ironwood
advancedrocketry:alien
quark:swampoak
quark:blossoming
silentgear:netherwood

just extract this to config/bonsaitrees:
[bonsaitrees.zip](https://github.com/thraaawn/BonsaiTrees/files/3638936/bonsaitrees.zip)

**Comment by hron84** [comment]
I think Heartstone mystical tree needs a shape too. In Glacial Awakening, the modpack creator already done the most of work, the tricky problem is that tree does not have a specific sapling (you grow it by using a magical item on any - vanilla? - sapling), GA creator added a ContentTweaker sapling item for work it around. I'm considering opening a ticket for the mod to add an optional sapling for the compatibility, but first I wanted to pop this topic up here to see if there is any alternative idea to support it.

**Comment by hron84** [comment]
Btw, as soon as I have some spare time, I will construct a pull request after some playtesting the uploaded shapes.

**Comment by Rogue238** [comment]
That's really great of you.

I haven't played around with Heartstone, but I like you idea.  Perhaps, you could right-click the item on any planted bonsai pot and it would change to the mystical tree.

**Comment by hron84** [comment]
@Rogue238 I don't think Bonsai pots has a special interaction like this.

**Comment by Rogue238** [comment]
I wish I knew more about java and modding.  It would be nice be able to create a mod specifically to provide that interaction.

**Comment by Shadow907G** [comment]
Any chance of apricorn trees from pixelmon reforged i would add them but dont understand how to

**Comment by gaminggirl** [comment]
Can I add a wish to, Candy World saplings

**Comment by IskallDoe** [comment]
What about adding support for Project: Vibrant journey's trees?

**Comment by Shinino** [comment]
So:  What is needed to make trees from other mods compatible?  I'm right there with the above about wanting support for Project: Vibrant Journey's trees as well.

**Comment by Rogue238** [comment]
It's not hard to make the trees compatible.  It's just editing a json file and going into a creative world to save the shapes.  I have fun doing it.  You can make the trees drop whatever you want.

**Comment by IskallDoe** [comment]
What if i first use the command /bonsaitree SaveTreeShape <sapling id> to save the shapes and then edit the json files? It works the same?

**Comment by Rogue238** [comment]
There's two json files, a type file and a shape file.  I always save the tree shape first and then edit that file, but the type file has to be edited by hand.  I tend to use a prewritten file and just change what I need.

**Comment by IskallDoe** [comment]
Could post an example of the prewritten file? I don't really know how i have to edit the type json.
Or it's a file available somewhere else?

**Comment by Rogue238** [comment]
> This is probably one of my very favorite mods. I've added quite a few trees, but like Xemnes-Keyethkateth, I have no idea how to do a pull request. I've tried, but I'm new to GitHub. I have tested all of them and they did work. So, here is my contribution and I hope someone finds this useful:
> 
> [bonsaitrees-chinjufumod.zip](https://github.com/thraaawn/BonsaiTrees/files/3511989/bonsaitrees-chinjufumod.zip)
> [bonsaitrees-fossil.zip](https://github.com/thraaawn/BonsaiTrees/files/3511992/bonsaitrees-fossil.zip)
> [bonsaitrees-quark.zip](https://github.com/thraaawn/BonsaiTrees/files/3511994/bonsaitrees-quark.zip)
> [bonsaitrees-PamsRedbud.zip](https://github.com/thraaawn/BonsaiTrees/files/3511995/bonsaitrees-PamsRedbud.zip)
> [bonsaitrees-PamsSpooky.zip](https://github.com/thraaawn/BonsaiTrees/files/3511997/bonsaitrees-PamsSpooky.zip)
> [bonsaitrees-StygianEnd.zip](https://github.com/thraaawn/BonsaiTrees/files/3511999/bonsaitrees-StygianEnd.zip)
> [bonsaitrees-Zoestria.zip](https://github.com/thraaawn/BonsaiTrees/files/3512001/bonsaitrees-Zoestria.zip)
> [bonsaitrees-afraidofthedark.zip](https://github.com/thraaawn/BonsaiTrees/files/3512005/bonsaitrees-afraidofthedark.zip)
> [bonsaitrees-defiled.zip](https://github.com/thraaawn/BonsaiTrees/files/3512007/bonsaitrees-defiled.zip)
> [bonsaitrees-evilcraft.zip](https://github.com/thraaawn/BonsaiTrees/files/3512012/bonsaitrees-evilcraft.zip)
> [bonsaitrees-Midnight.zip](https://github.com/thraaawn/BonsaiTrees/files/3512015/bonsaitrees-Midnight.zip)
> [bonsaitrees-spookybiomes.zip](https://github.com/thraaawn/BonsaiTrees/files/3512016/bonsaitrees-spookybiomes.zip)
> [bonsaitrees-TolkienTweaksMobs.zip](https://github.com/thraaawn/BonsaiTrees/files/3512018/bonsaitrees-TolkienTweaksMobs.zip)
> [bonsaitrees-Aether.zip](https://github.com/thraaawn/BonsaiTrees/files/3512122/bonsaitrees-Aether.zip)
> [bonsaitrees-erebus.zip](https://github.com/thraaawn/BonsaiTrees/files/3512127/bonsaitrees-erebus.zip)

Just unzip any of these zip files I've already made up and check them out.  There's numerous types examples if you download them all.  There was a wiki on this site a while back that taught how to do it, but I can't find the link any more.  One thing you need to be sure of it the "type" of tree is the same in the type and the shape file.  I'm bad at explaining.  In the type file, you can say which sapling you want to plant and what it will drop (STICK, WOOD, LEAVES, SAPLING, FRUIT, or CUSTOM).  In the shape file, you can tell what it will look like when it grows in the pot.  You can do that manually, but I recommend using the saveTreeShape command.

I forgot to mention in the first post that I don't care if someone else uses the json files I created, even for their own modpack.  Most of it was just editing the original files in the jar, anyway.

**Comment by Shinino** [comment]
Given that this hasn't been updated in a while (and the mod hasn't been updated in 18 months+), how would one add those zip files to make it work?  Or is this something that has to be done via java?

**Comment by Rogue238** [comment]
> Given that this hasn't been updated in a while (and the mod hasn't been updated in 18 months+), how would one add those zip files to make it work? Or is this something that has to be done via java?

Mine are set up so you can just add them directly into your instance folder when you unzip them.  It should look like this:

(Your game instance path)
 .../config
....../ bonsaitrees
........./shapes.d
............/modname_treename001.json
............/modname_treename002.json
........./soils.d
............/modname_soilname.json
........./types.d
............/modname_treename.json
........./ setting.cfg

I'm sorry if this isn't very clear.  Let me know if you have any problems installing them.

**Comment by Shinino** [comment]
Appreciate it.  I'm going to test it now, then figure out what other mods in the pack I'm using (RAD) need trees and see if it's something I can puzzle out.  If not, I'll add the list here, and hopefully smarter people can help :)

Anyone know where MC saves the json files when I create shapes?

**Comment by Shinino** [comment]
So after testing, these all work, but I'm having an issue trying to get the remaining trees for RAD (ones from Caverns II, Rustic, The Twilight Forest, TropicCraft and Unique Items).

1) I don't know where it saves the JSON
2) How do you get the tree-type-ID?  I can get the sapling ID (and log/leaves) by looking at them in game -- but not the tree type ID.  If I have that, I might be able to get those five mods going as well.

**Comment by Shinino** [comment]
> This is probably one of my very favorite mods. I've added quite a few trees, but like Xemnes-Keyethkateth, I have no idea how to do a pull request. I've tried, but I'm new to GitHub. I have tested all of them and they did work. So, here is my contribution and I hope someone finds this useful:
> [bonsaitrees-Aether.zip](https://github.com/thraaawn/BonsaiTrees/files/3512122/bonsaitrees-Aether.zip)

So the trees in the Aether are ... not right. 

Skyroot Trees drop regular sticks, while Golden Oak trees drop Skyroot sticks, Skyroot logs, as well as other stuff.  I can fix this on my end (moving Skyroot sticks to Skyroot trees as well as the logs) and adding leaves and such.  Ideas?

I think part of the issue is that the item IDs are very generic -- the Skyroot leaves are aether_leaves, the Skyroot logs are aether_log -- instead of Skyroot_leaves/Skyroot_logs.  The same applies with the Golden Oak -- so part of the problem is not with the JSON files, but with Aether's naming convention.  I can definitely ping them to see if anything can be done.  I would definitely say that instead of skyroot_stick, though, the golden oak should just drop 'stick'.

**Comment by Shinino** [comment]
So back to Skyroot:  They should drop White Apples as well.  So Skyroot Logs (good luck to us there), Skyroot Stick (easy), Skyroot leaves (good luck) and White Apples (easy, I think).

Golden Oak: Golden Oak Wood (ha), Golden Oak leaves (also ha), normal sticks (easy) and the Golden whatever it is (not in game, already drops it).    I'll do some tweaking, and if I can get it working, I'll post the file here for everyone.

**Comment by Rogue238** [comment]
I am so sorry!  I just saw you posted!  Busy few days for me irl.

In the game, there are commands to save the tree.  It's been awhile.  I've been taking a break from Minecraft.  So, you save the tree in game and the json will appear in the shapes.d folder.  There will be a tree ID in there under name.  You can change it, but it needs to be the same in the types.d json.

As for the ID, no, they aren't generic.  They have data IDs as well.  It will only drop the specific item you tell it too.  I use JEI to check the data, which is sometimes called damage ID for some reason.

Fill free to make all the files work for you.  I may have forgotten the white apples come from Skyroot Trees. lol   Sorry.  The golden amber is a very rare drop from chopping down the Golden Oak tree.  I used Skyroot sticks because the Golden Oak drops Skyroot logs in the game.  It should drop both Skyroot logs and Golden Oak logs, though.

Most of the trees in Twilight Forest should work naturally.  The problem is the big trees are too big to make the shape files look nice.  I have tried several times.  It just cuts them off and they look weird.

I have to go get ready for work, but I'll check in when I get home.

**Comment by Shinino** [comment]
Right, I think the issue with Aether trees is that Aether -itself- has bad naming on those trees, not anything with Bonsai.  I can fix some of the drops for them, but I can't guarantee the wood/leaves for that reason.

**Comment by Shinino** [comment]
more poking at Aether:  Looking at the jar itself, I found the aether_log stuff, and it makes a callout for the following models: aether_legacy:golden_oak_log and aether_legacy:skyroot_log -- I'm going to poke around and see if these are in-game in a bit, and if so, this will/should be an easy change to make.  If so, I'll test and upload.'

Update:  No, you can't give either golden_oak_log or skyroot_log -- so this would have to be a change to Aether Legacy itself and THEN updating the compat patch for Bonsai Trees.

So it would require a modification to the Aether's source code and a recompile to split the two out.    That said, here are updated jsons for the trees (in types.d):
[aetherlegacy_skyroot.zip](https://github.com/thraaawn/BonsaiTrees/files/7247251/aetherlegacy_skyroot.zip)

**Comment by Shinino** [comment]
Working on Caverns II, Rustic,  TropiCraft and Unique Items, Vibrant Journey)

I found the shape file, but need to figure out how to do type, and also if any of these require special soil (and how to tell)

(update)
Now have shape files for all of the trees for those 4 mods -- have to figure out how to determine what drops from each -- ideas?

**Comment by Rogue238** [comment]
I don't know all the mods.  What I usually do is look inside a type file and just replace it with whatever I want, making sure to save the file under a different name.  You can make the trees drop anything and everything as long as you can get the item id and the damage id.  Soils are called at the bottom of the type file.  If there's nothing about soil, then it defaults to regular dirt and grass, I believe.

Oh, I wouldn't look in the jar file.  Use JEI to find the item ID and damage values.  I have never had any problems getting it to drop the aether logs that I want.

**Comment by Shinino** [comment]
> I don't know all the mods. What I usually do is look inside a type file and just replace it with whatever I want, making sure to save the file under a different name. You can make the trees drop anything and everything as long as you can get the item id and the damage id. Soils are called at the bottom of the type file. If there's nothing about soil, then it defaults to regular dirt and grass, I believe.
> 
> Oh, I wouldn't look in the jar file. Use JEI to find the item ID and damage values. I have never had any problems getting it to drop the aether logs that I want.

I got the Aether stuff fixed.  I'm working on the other mobs now.  I can handle making types, it's more trying to figure out what everything drops -- I'm growing all of the trees in creative though, and it looks like all of them are 'wood', 'sticks', 'leaves', and 'saplings', so I should be okay.  It's more just making sure on stuff.

**Comment by Rogue238** [comment]
Okay.  That's great.  :)  Some of the Tropicraft trees should also drop 'fruit.'   Good luck and have fun!
