### ISSUE TITLE
please make for 1.16.4

### ISSUE THREAD

**Issue by QuackenAudio** [thraaawn/BonsaiTrees#220]
please make for version 1.16.4

**Comment by tails1974seeyounextgame** [comment]
i agree. also why the heck do websites other than curseforge havea texture and text version of 16.x versions but no files? latest it shows is 15.5

**Comment by Oct0bass** [comment]
"Websites other than curseforge" aren't a good place to get mods (unless they're the authors official site).  They might contain malware and such, and they're highly unlikely to be under the mod author's control.  I agree 1.16.4 would be ncie.

**Comment by marios-andr** [comment]
1.16.4 Would be very nice indeed.

**Comment by tails1974seeyounextgame** [comment]
im a nifty coder and can help i think. any particular reason no 16.4 yet?

**Comment by masternetra** [comment]
+1 For support for 1.16.

**Comment by masternetra** [comment]
> "Websites other than curseforge" aren't a good place to get mods (unless they're the authors official site). They might contain malware and such, and they're highly unlikely to be under the mod author's control. I agree 1.16.4 would be ncie.

- Nexusmods is fine, but of course your not going to find a lot (at least not a lot of minecraft mods anyway) there sense the vast majority of mods are at curseforge.

**Comment by PatFussy69** [comment]
> im a nifty coder and can help i think. any particular reason no 16.4 yet?

if I were you id make another thread or try to get in contact with the devs directly, but I think that as these updates have gotten significantly larger recently it has become more and more difficult to update mods to the newest versions. I remember a big issue with Tinkers was that they basically had to rebuild the entire mod just to update from 1.12. I could definitely be wrong on this though, just my take on this bc of other mods I've seen that haven't been updated in a while.

**Comment by Oct0bass** [comment]
Forge was completely rewritten between 1.12 and 1.14, which means most mods
had to do significant rewriting too.  Most updates redo certain parts of
the game but barely change others.  1.15 I think changed rendering, 1.16
reworked biomes and dimensions etc.  For a mod like bonsai trees i don't
think there should be a crazy amount of work to port to 1.16, so the dev is
probably just busy with life or something.  I could be wrong though
