### ISSUE TITLE
[1.14.4] The textures of the trees in the bonsai pots are randomly changed

### ISSUE THREAD

**Issue by Josegamer316** [thraaawn/BonsaiTrees#225]
![Captura de pantalla (257)](https://user-images.githubusercontent.com/81001220/112332907-2179bf80-8c88-11eb-9b4c-49fb3acc47fc.png)
![Captura de pantalla (258)](https://user-images.githubusercontent.com/81001220/112332911-22125600-8c88-11eb-9fd3-8b4f9768f18e.png)
![Captura de pantalla (259)](https://user-images.githubusercontent.com/81001220/112332915-22aaec80-8c88-11eb-98e5-006e3704106a.png)
![Captura de pantalla (260)](https://user-images.githubusercontent.com/81001220/112332961-2b9bbe00-8c88-11eb-8e97-2391a0181ea7.png)

**Comment by davenonymous** [comment]
Sorry, I'm personally not supporting any versions below the upcoming 1.18.1 version.
Maybe someone else wants to pick things up for older versions - I simply don't have the time.
