### ISSUE TITLE
Mod was reported as trojan by avast

### ISSUE THREAD

**Issue by Eugeniu-N** [thraaawn/BonsaiTrees#226]
bonsaitrees-1.1.4-b170.jar (from project ozone 3) was reported as a trojan by avast

Not sure if I should be worried, most likely it's a false positive, was curious what could possibly cause this issue

**Comment by davenonymous** [comment]
Sorry, I'm personally not supporting any versions below the upcoming 1.18.1 version.
Maybe someone else wants to pick things up for older versions - I simply don't have the time.
