### ISSUE TITLE
[1.12.2] Bonsai Dupe on break

### ISSUE THREAD

**Issue by aldinh777** [thraaawn/BonsaiTrees#227]
I am currently using the latest release bonsai version on 1.12.2, "bonsaitrees-1.1.4-b170.jar"

Whenever i break the hopper bonsai, it drop 2 hopper bonsai, also 2 dirt and 2 sapling when there is one before

**Comment by davenonymous** [comment]
Sorry, I'm personally not supporting any versions below the upcoming 1.18.1 version.
Maybe someone else wants to pick things up for older versions - I simply don't have the time.
