### ISSUE TITLE
Tutorial wiki on how to add custom things

### ISSUE THREAD

**Issue by vizthex123** [thraaawn/BonsaiTrees#228]
Title. It would be nice to have documentation on how to add soils & whatnot for 1.12.2 (and other versions)

**Comment by Nikinak33** [comment]
I'm wondering the same thing.

**Comment by davenonymous** [comment]
See the readmes for the corresponding versions.
E.g. for 1.12: https://github.com/thraaawn/BonsaiTrees/blob/master/README.md

**Comment by vizthex123** [comment]
not as accessible as it should be imo, but alright.
