### ISSUE TITLE
visual glitch for 1.12.2, jar version 1.1.4-b170

### ISSUE THREAD

**Issue by okaniwa-se** [thraaawn/BonsaiTrees#229]
![2021-05-16_13 23 50](https://user-images.githubusercontent.com/83481317/118408194-102aaf00-b64a-11eb-9f50-93e3150db5a2.png)
every time i change my view the texture for the dirt moves around sporadically, i had optifine installed and i uninstalled it but it's still happening.

**Comment by davenonymous** [comment]
Sorry, I'm personally not supporting any versions below the upcoming 1.18.1 version.
Maybe someone else wants to pick things up for older versions - I simply don't have the time.
