### ISSUE TITLE
I made an 1.16 version of this mod.

### ISSUE THREAD

**Issue by heipiao233** [thraaawn/BonsaiTrees#231]
But when I want to create a pull request, there is no branch for the code of 1.16. Please create that branch, thanks.

**Comment by heipiao233** [comment]
And Libnonymous.

**Comment by Cyphexd** [comment]
can u share u discord pls ?

**Comment by heipiao233** [comment]
Sorry but I am in the People's Republic of China, so I unable to connect to some websites for political reasons.

**Comment by Cyphexd** [comment]
oh okay
do u have other contact ?

**Comment by fuzzyweapon** [comment]
yes please.

**Comment by fuzzyweapon** [comment]
So I built @heipiao233 's 1.16 but I have never used this mod outside of using that build.  There are some crashes (and seemingly just hangs) happening for me anytime I bring up configuration menus or do things like bringing up the bonsai maker.

I have no idea if these bugs were in the last release or not, but I assume the community does readily, but I thought I'd put this here just for visibility on the state of it.

**Comment by davenonymous** [comment]
Hey thanks for your effort!

Sorry, I'm personally not supporting any versions below the upcoming 1.18.1 version.
Maybe someone else wants to pick things up for older versions - I simply don't have the time.
