### ISSUE TITLE
[1.12.2] Soil invisible when using connected textures

### ISSUE THREAD

**Issue by BriceFable** [thraaawn/BonsaiTrees#232]
Title. 

I have made a custom soil (sand) and it appears invisible when I am using Connected Textures Mod with their Connected Textures Pack. It shows up perfectly fine with the texture pack disabled.

CTM: https://www.curseforge.com/minecraft/mc-mods/ctm
CTP: https://www.curseforge.com/minecraft/texture-packs/ctp

**Comment by davenonymous** [comment]
Sorry, I'm personally not supporting any versions below the upcoming 1.18.1 version.
Maybe someone else wants to pick things up for older versions - I simply don't have the time.
