### ISSUE TITLE
[1.12.2] Hopping Bonsai Pots bypasses redstone-disabled hopper

### ISSUE THREAD

**Issue by VarianArdell** [thraaawn/BonsaiTrees#233]
Minecraft: 1.12.2
Forge: 14.23.5.2854
Bonsai Trees: 1.1.4-b170

As the title states, hopping bonsai pots override the default behaviour of hoppers, which is to not accept any input when said hopper has a redstone signal. Any plans to rectify this, or at least make it an option in the configs?

**Comment by davenonymous** [comment]
Sorry, I'm personally not supporting any versions below the upcoming 1.18.1 version.
Maybe someone else wants to pick things up for older versions - I simply don't have the time.
