### ISSUE TITLE
How to add compatibility with other mods for 1.12.2

### ISSUE THREAD

**Issue by lRoberth** [thraaawn/BonsaiTrees#234]
Don't expect someone else adding compatibility with [TreeOres](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2242983-treeores-1-12-2-finally-back-version-0-1-1-11-2-1), so I'm looking at adding it myself. Could I have some explanation on how these mods works, where I have to look at, to add compatibility with that mod on my own?

I do have knowledge of coding, but not Minecraft mods.

**Comment by davenonymous** [comment]
See this readme: https://github.com/thraaawn/BonsaiTrees/blob/master/README.md
