### ISSUE TITLE
duplication glitch

### ISSUE THREAD

**Issue by Zanna40** [thraaawn/BonsaiTrees#237]
using the carry on mod on bonsai tree , you can place infinite bonsai with the loot inside, you can't place the bonsai and the only way of stopping this glitch is with the death

**Comment by davenonymous** [comment]
Thanks for the report. Will be fixed in the next release.

**Comment by jstansel** [comment]
I came to github with the same report. I was able to remove the carry on jar from my mods folder (and restart the game of course) to stop the glitch.
