### ISSUE TITLE
[1.18.1] Placing down a Bonsai Pot, placing a Grass Block in it. Then right-clicking it crashes you.

### ISSUE THREAD

**Issue by Gbergz** [thraaawn/BonsaiTrees#238]
Title ^
Placing down a Bonsai Pot, placing a Grass Block in it. Then right-clicking it crashes you.

## Versions
Forge: 39.0.14
Minecraft: 1.18.1
Bonsai: 3.0.0 | https://www.curseforge.com/minecraft/mc-mods/bonsai-trees/files/3598630

Crash-Report: https://gist.github.com/Gbergz/73072110de82199b4d00d5fcbbb29508

**Comment by Gbergz** [comment]
Known?

**Comment by davenonymous** [comment]
So far unable to reproduce.
Not sure which mod interaction is causing this.

**Comment by Kirbyte377** [comment]
This is happening to me as well with the 3.0.1 version

**Comment by TOLoneWolf** [comment]
just figured out this was what is happening for me as well with grass blocks. was working fine then bam "Block being tesselated".
do have a crash report that complains about chisels & bits when also doing the tesselated block for bonsai.
[crash-2022-01-26_20.58.48-server.txt](https://github.com/thraaawn/BonsaiTrees/files/7947505/crash-2022-01-26_20.58.48-server.txt)

**Comment by TOLoneWolf** [comment]
Did a small test set of mods and as soon as I removed chisel and bits it has not had any crashes.
The timing of when it decides to crash is a bit random. Having 4 pots down seems to trigger it quick enough.

Your UI (rainbow) also is being replaced with the vanilla interface when JEI is installed.
Chisel and bits tool menu instantly crashes with bonsaitrees3 but works fine on its own.

mods use to test:
```
forge-39.0.59
bonsaitrees3-3.0.0.jar
ChiselsBits-forge-1.18.1-1.2.77-universal.jar
jei-1.18.1-9.2.3.82.jar
notenoughcrashes-4.1.4+1.18.1-forge.jar
time-in-a-bottle-2.1.0-mc1.18.1.jar
```

**Comment by davenonymous** [comment]
Thank you very much! This will help a lot in debugging!

**Comment by davenonymous** [comment]
That commit probably fixes this issue.

> Your UI (rainbow) also is being replaced with the vanilla interface when JEI is installed.

🤔  The GUI should not look like a rainbow. That's a bug as well. Will look into it.

**Comment by davenonymous** [comment]
Whoop Whoop. All bugs fixed. I'll try to get a release out today.
Again, thanks for your help and reports!

**Comment by TOLoneWolf** [comment]
nice, glad it helped.
