### ISSUE TITLE
Difficulty Generating Missing Shapes

### ISSUE THREAD

**Issue by BryanBoru** [thraaawn/BonsaiTrees#24]
In a superflat with cheats enabled. 

typed into chat - `/bonsaitrees generateMissingShapes yes` 

[![Screenshot from Gyazo](https://gyazo.com/2d853ffe0cf976582b2a6b2958684908/raw)](https://gyazo.com/2d853ffe0cf976582b2a6b2958684908) 

I am unsure what else I can do to make it possible to have this code work?
I tried changing the shapes and types folders from Read-Only to open, no change.
I tried with and without cheats enabled.
Any advice?

Playing on MultiMC 0.6.0 with a custom modpack

**Comment by thraaawn** [comment]
You'll need to be in creative mode.
