### ISSUE TITLE
[1.18.1] Pod running endless

### ISSUE THREAD

**Issue by UdoMorgenstern** [thraaawn/BonsaiTrees#240]
Using automated harvesting with an axe, the pod will never stop harvesting and re-growing trees even if all output slots are filled.
Only way to stop it (ifaik) is to remove the axes.

Suggestion: Would also be great if the pods could be turned off by a redstone signal.

**Comment by UdoMorgenstern** [comment]
Minor Multiplayer info: If one person remove an axe, the growing animation will still be visible for a 2. person around as long as the 2. person does not look into the pod's inventory. After that the animation stops

**Comment by davenonymous** [comment]
Thanks for the reports. I will look into those for the next release.
