### ISSUE TITLE
bonsai tree has been categorized as a trojan by my antivirus

### ISSUE THREAD

**Issue by kill4588** [thraaawn/BonsaiTrees#241]
type:
Generic/Trojan.Generic.HgAASSEA

description:
Generic/Trojan.Generic.HgAASSEA

scanning motor:
360scan

file location:
D:\MC\Instances\Dungeons Dragons and Space Shuttles\mods\bonsaitrees-1.1.4-b170.jar
D:\MC\Backups\Project Ozone 3 A New Way Forward\mods\bonsaitrees-1.1.4-b170.jar
D:\MC\Backups\Roguelike Adventures and Dungeons (2)\mods\bonsaitrees-1.1.4-b170.jar
D:\MC\Backups\Seablock Rustic Waters (1)\mods\bonsaitrees-1.1.4-b170.jar

file footprint(MD5):
136677befb5a253b867c8fde52bfa11b

#no way to make the mod working because file is quarantined, didn't try with other version of the mod

**Comment by davenonymous** [comment]
¯\\\_(ツ)_/¯ no idea why that's happening. add an exception to your virus scanner maybe? it isn't a trojan...
