### ISSUE TITLE
[1.18.1] Fabulous Graphics

### ISSUE THREAD

**Issue by WenXin20** [thraaawn/BonsaiTrees#246]
`Forge v39.0.59`
`Bonsai Trees v3.0.0`

Trees do not render with fabulous graphics enabled. Changing it back to fancy fixes it.

![2022-01-29_15 16 22](https://user-images.githubusercontent.com/12000593/151677807-11d4bcdd-1e3b-49fc-94af-d574032e982d.png)

**Comment by davenonymous** [comment]
Thanks for the report. Will be fixed in the next release :)

**Comment by WenXin20** [comment]
Thanks!
