### ISSUE TITLE
[1.18.1] Switching Saplings

### ISSUE THREAD

**Issue by WenXin20** [thraaawn/BonsaiTrees#251]
`Forge v39.0.59`
`Bonsai Trees v3.0.2`

Switching the sapling will keep the fully grown tree instead of resetting the growth.

https://user-images.githubusercontent.com/12000593/152401571-2d3bd699-3a08-4a3c-b014-3517b1f8d79a.mp4

**Comment by davenonymous** [comment]
Oops. Will look into it soon.

**Comment by davenonymous** [comment]
Fixed, will be in the next release.

**Comment by WenXin20** [comment]
Thanks!
