### ISSUE TITLE
BonSai Tree 3 World Load Crash and tick lag

### ISSUE THREAD

**Issue by PernDragon** [thraaawn/BonsaiTrees#254]
I tried to use this mod with other mods I have and I at first noticed a slight hesitation about once a minute or so, figured maybe it was due to loading new Chunks at first.

Then today I went to load an old world, did that successefully so closed that world and opened another to have a crash.  
I read through my logs to find that BonSai Tree 3 did indeed crash the system.  I'm hoping to help resolve the problem as I love your mod.

I'm including my crash report and my long list of mods I and my family use on our home server
[crash-2022-02-03_00.00.17-fml.txt](https://github.com/thraaawn/BonsaiTrees/files/8003992/crash-2022-02-03_00.00.17-fml.txt)
.

**Comment by PernDragon** [comment]
Mods as follows 

Additional Lanterns
Alex's Mobs
AmbientSounds
Amplifed Nether
Appleskin
Aquaculture
Aquatic Torches
AutoRegLib
Balm
Biomese O Plenty
Blue Skies
Buddy Cards
Caelus
Carpet Stairs Mod
Catalogue
Chalk
Chunk Loaders
Citadel
Cloth Config
Configured
Controllable
CraftTweaker
CreatFA
CreativeCore
Croptopia
Curios
CuriosElytra
Dungeons Arise
Elemental Swords
Enchantment Descriptions
Ender Chest
Falling Leaves
Fast Leaf Decay
FlyWheel
Framework
Funriture
GlobalXP
Gobber2
Goblin Traders
Golden Hopper
Inverntory Sorter
Iron Chest
Iron Furnaces
JEI
MCW Lights
MCW Roofs
Multi
Nether PortalFix
Optifine
Patchouli
Placebo
Quark
Quark Oddities
Recall
Refined Storage
Refined storgar Addons
ShetiphianCore
Silent Gear
Silent Lib
Simple Magnets
Sit
Sky Villages
Smarter Farmers
Sophisticaed Backpacks
Storage drawers
Structure Gel
SuperMartijn Config Lib
SuperSmartijn Core Lib
TerraBlender
Tetra
Textirel Backup
TheOne Prob
Trash Slot
WitherSkeleton Tweaks
World Edit
Xaeros Minimap
Xaeros World Map.

**Comment by davenonymous** [comment]
You are missing [libnonymous](https://www.curseforge.com/minecraft/mc-mods/libnonymous).

**Comment by osirus31** [comment]
This looks like a version issue with the dependent [Libnonymous](https://www.curseforge.com/minecraft/mc-mods/libnonymous).  Class not found likely means you are using a older version of this mod that does not have the class that Bonsai uses.

Try updating the version of [Libnonymous](https://www.curseforge.com/minecraft/mc-mods/libnonymous) (backup first though as that might break your other mods that use that library mod.
