### ISSUE TITLE
[1.18.1] Crash on game start - java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by holty07** [thraaawn/BonsaiTrees#256]
Hi there, I am receiving a crash on start-up and am getting an error related to Bonsai Trees 3. Let me know if there is any more info I can provide. Crashlog attached.
[crash-2022-02-05_08.33.31-fml.txt](https://github.com/thraaawn/BonsaiTrees/files/8006641/crash-2022-02-05_08.33.31-fml.txt)

**Comment by davenonymous** [comment]
Caused by 1: java.lang.NoClassDefFoundError: com/davenonymous/libnonymous/compat/top/ITopInfoProvider

You are missing [libnonymous](https://www.curseforge.com/minecraft/mc-mods/libnonymous).
