### ISSUE TITLE
[Suggestion] [1.18.1] Allow to Set Required Tool

### ISSUE THREAD

**Issue by enigmaquip** [thraaawn/BonsaiTrees#257]
I would think either just forge tags in the sapling recipe or a whole tool recipe system similar to dirt. This would allow for things like the blue skies trees requiring blue skies axes. Their whole system is nerfing non BS tools while in their dimensions. Could also allow for things not tree related.

**Comment by davenonymous** [comment]
This sounds like a great idea. Will look into this!
