### ISSUE TITLE
java.lang.reflect.InvocationTargetException: null

### ISSUE THREAD

**Issue by Hulmee** [thraaawn/BonsaiTrees#258]
when running the forge server and client i get the below error 
java.lang.reflect.InvocationTargetException: null

**Comment by UnAssumedAlias** [comment]
Hey friend, i just had this problem did you download the libnonymous libs???
https://www.curseforge.com/minecraft/mc-mods/libnonymous

**Comment by davenonymous** [comment]
No log & probable solution presented. Closing.
