### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by westski502** [thraaawn/BonsaiTrees#261]
Hi, I just got the newest version of Bonsai Trees and Libnonymous and I get a crash on startup. I also have plenty of other mods installed. The mods worked together perfectly until I started getting a random crash. I decided to update my mods to see if it would work then. First file is from updating, second file is the crash I started getting before I updated.
[crash-2022-02-11_15.42.05-fml.txt](https://github.com/thraaawn/BonsaiTrees/files/8052076/crash-2022-02-11_15.42.05-fml.txt)
[crash-2022-02-11_15.33.27-server.txt](https://github.com/thraaawn/BonsaiTrees/files/8052091/crash-2022-02-11_15.33.27-server.txt)

**Comment by davenonymous** [comment]
Oh shoot. I uploaded the deobfuscated version.
Fixing immediately.

**Comment by davenonymous** [comment]
Sorry for that. Fix is released and already approved on curseforge.
Thanks to that quick report only 32 people fell into that trap. 🙇
