### ISSUE TITLE
World Loading Crash

### ISSUE THREAD

**Issue by westski502** [thraaawn/BonsaiTrees#262]
Hi again! Thank you for fixing the last issue so quickly, I appreciate it! I have a different crash than the previous one. Bonsai Trees and Libnonymous are both updated to the newest version. Other mods were installed and everything was compatible until I got a random crash. I fixed this issue once by removing Bonsai Trees, starting up my world, and adding Bonsai Trees back. After playing for a few hours, I started to get the crash again.
[crash-2022-02-11_16.21.21-server.txt](https://github.com/thraaawn/BonsaiTrees/files/8052191/crash-2022-02-11_16.21.21-server.txt)

**Comment by davenonymous** [comment]
Oops, wrong button. This jar should fix the problem 🤞:
[libnonymous-2.0.4.jar.zip](https://github.com/thraaawn/BonsaiTrees/files/8052313/libnonymous-2.0.4.jar.zip)
Can you retest it with this build please? (don't forget to unpack the zip first 😉 github doesn't allow direct jar uploads.)

**Comment by westski502** [comment]
I can't seem to find any issues or crashes anymore. Sorry for the late reply. Thank you so much!
