### ISSUE TITLE
[Suggestion] 1.18.1 Tinker's trees support

### ISSUE THREAD

**Issue by Kysha7** [thraaawn/BonsaiTrees#263]
As the title says, support for tinke's, it not only has tools but also trees that are very useful to use together with this mod.

I can only say that I speak for version 1.18.1 forge

If this is possible, that would be great.

**Comment by davenonymous** [comment]
Tinkers should be support since version 3.0.4. Are you running an older version or is there a bug somewhere?

**Comment by Kysha7** [comment]
Hello, excuse me, I overlooked version 3.0.4

It works perfect
