### ISSUE TITLE
[BUG/CRASH] [1.12.2] Renderer runs several times into an "Already Building!" Issue

### ISSUE THREAD

**Issue by Speecker** [thraaawn/BonsaiTrees#264]
What i expected:
 - A clean working rendering without issues

What happened:
 - As described does Bonseitree3 sometimes fail to render correctly and therefore makes the Game Crash into main menu but you have to reload the full Game anyway as there will persist a flickering Glitch after rejoining your World.

See the Crash-Report for full Details:
https://pastebin.com/nUhGyedc

**Comment by davenonymous** [comment]
a) Remove optifine and see if that helps. Always remove optifine and try again before reporting bugs, please.
b) 1.12 isn't supported anymore, i.e. there 100% won't be a new bonsai trees release for it.
