### ISSUE TITLE
Crash within ATM7.45/AllTheModium.

### ISSUE THREAD

**Issue by lShanghaiMoonl** [thraaawn/BonsaiTrees#267]
This is the crash report:

-The game crashed whilst rendering overlay
Error: net.minecraft.ResourceLocationException: Non [a-z0-9/._-] character in path of location: bonsaitrees3:models/tree/allthemodium/soul 4.json
Exit Code: 255-

Seems to be an issue with a non-existent/accessable file that showed up under my directory as:

"bonsaitrees3:models/tree/allthemodium/soul 4.json" 

The literal space between "soul" and "4" is what stood out to me.... Idk lmk what you think...

 let me know if i can send anything else :)

Here is the log:

[latest.log](https://github.com/thraaawn/BonsaiTrees/files/8160245/latest.log)

**Comment by lShanghaiMoonl** [comment]
this unfortunatley leaves me unable to launch the atm7 Modpack

**Comment by lShanghaiMoonl** [comment]
MacBook Pro (13-inch, 2016, Two Thunderbolt 3 ports) 2 GHz Intel Core i5 8 GB 1867 MHz LPDDR3 Intel Iris Graphics 540 1536 MB

- ATM7 Modpack (Version 0.2.45)
- Bonsaitrees (Version 1.18.1-429)

**Comment by davenonymous** [comment]
`bonsaitrees3:models/tree/allthemodium/soul 4.json` is not part of the actual bonsai trees mod, but must be an addon by the modpack? The whitespace is the issue. The file should be called soul.json - weird that it isn't in your instance.

There is no reference to "soul 4" anywhere in the latest atm7 download. 🤔 

See https://github.com/AllTheMods/ATM-7/issues/537
