### ISSUE TITLE
Port to 1.18.2

### ISSUE THREAD

**Issue by Demikiev** [thraaawn/BonsaiTrees#268]
Hi ! I just put BonsaiTrees3-3.0.4.jar along with libnonymous-2.0.5.jar in my mod folders but it won't work.

The only other mod i have is preview_OptiFine_1.18.2_HD_U_H6_pre1.jar and I am using Forge 40.0.3 for 1.18.2

Here is the crash report :

[crash-2022-03-05_21.56.31-fml.txt](https://github.com/thraaawn/BonsaiTrees/files/8191476/crash-2022-03-05_21.56.31-fml.txt)

I'm not used to using mods so sorry if the problem is something stupid ._.

**Comment by davenonymous** [comment]
The mod is currently only supported on 1.18.1.
The port to 1.18.2 is in progress though. Will probably release tomorrow.

**Comment by Demikiev** [comment]
Oh ok, thanks. I'll just wait for it then :)

**Comment by davenonymous** [comment]
This is done and will be available on curseforge once approved.
