### ISSUE TITLE
Duping Glitch

### ISSUE THREAD

**Issue by TheReflexiveGamer** [thraaawn/BonsaiTrees#269]
When using the carryon mod for 1.18.1 you can infinitely dupe bonsai pots and anything inside them. except you can NEVER place the actual pot down. Even on death it still thinks you have it in your hand.

**Comment by davenonymous** [comment]
What Bonsai Trees version are you using? This should be fixed since 3.0.3 (see #237).
Just retested this. Yupp. Still working fine:

https://user-images.githubusercontent.com/205210/156942853-d14dfd8f-a406-4714-bc47-ec21658020a3.mp4
