### ISSUE TITLE
[Suggestion] Support ItemDucts (Thermal Dynamics) as Output Target for Hopping Bonsai Pots

### ISSUE THREAD

**Issue by Samtrion** [thraaawn/BonsaiTrees#27]
As the title suggests, it would be nice. Alternative to Chests.

**Comment by thraaawn** [comment]
All ItemHandlers should already be supported.

Did you actually try to use ducts and they didn't work? This sounds like a feature suggestion and not like a bug report and I'm confused.

**Comment by Samtrion** [comment]
As my title said, it is a feature suggestion. :)

Yes, I have already tried it, unfortunately without success.
Will make it available as a PR during the day.

**Comment by thraaawn** [comment]
Ah I see. It should be a bug report though, since it should not matter what kind of inventory is placed below. ;)

Regarding the issue itself: Hmm. Weird. Did you already figure out why it doesn't output into the ducts ItemHandler? Curious what this is caused by.

**Comment by Samtrion** [comment]
The problem is that ItemDucts are no ItemHandlers. ItemDucts only connect and do there thing, if the TileEntity has the capability ITEM_HANDLER_CAPABILITY.
Of course, this does not work because the bonsai pot doesn't have this capability.

EnderIO Conducts would also work with the PR.
