### ISSUE TITLE
Negative ticks required when using Efficiency and Custom soil

### ISSUE THREAD

**Issue by RoyalReject** [thraaawn/BonsaiTrees#270]
I was testing the limits of custom soil and found an instance that can cause requiredticks to become negative,
![2022-03-06_17 03 37](https://user-images.githubusercontent.com/32550284/156946157-1c1a4514-fd7a-4c72-807a-6e647b236be5.png)
![2022-03-06_17 03 32](https://user-images.githubusercontent.com/32550284/156946161-8341e4bc-c963-46ce-a60c-e8a3e59ec26d.png)

Custom soil:
`{
    "type": "bonsaitrees3:soil",
    "tickModifier": 0.1,
    "soil": {
        "item": "minecraft:stone"
    },
    "compatibleSoilTags": [
        "grass"
    ],
    "display": {
        "block": "minecraft:stone"
    }
}`

**Comment by RoyalReject** [comment]
For max vanilla efficiency lowest tickModifier you can use is 0.3, it will go negative with 0.1 and 0.2

**Comment by davenonymous** [comment]
Thanks for the report. Fix will be in the next release.
