### ISSUE TITLE
Support for 1.16.5 and Pixelmon updated to 1.16.5?

### ISSUE THREAD

**Issue by ceschiavolim** [thraaawn/BonsaiTrees#274]
Hello, is there a possibility that this mod will receive support for 1.16.5 and updates from what will be released in Pixelmon for Apricorns 1.16.5?

**Comment by Docwho1983** [comment]
Yes please would love a 1.16.5 version

**Comment by OceanRift** [comment]
WHERE IS 1.16.5 ?? Its a joke??
