### ISSUE TITLE
Fails to load

### ISSUE THREAD

**Issue by AbsoluteAnton** [thraaawn/BonsaiTrees#279]
The mod fails to load and give me this in crash log:
Mod File: bonsaitrees3-3.0.4.jar
	Failure message: Bonsai Trees 3 (bonsaitrees3) has failed to load correctly
		java.lang.reflect.InvocationTargetException: null
	Mod Version: 3.0.4
	Mod Issue URL: https://github.com/thraaawn/BonsaiTrees/issues
	Exception message: java.lang.ClassNotFoundException: com.davenonymous.libnonymous.compat.top.ITopInfoProvider
Stacktrace:

**Comment by davenonymous** [comment]
Install [libnonymous](https://www.curseforge.com/minecraft/mc-mods/libnonymous).
