### ISSUE TITLE
None of the bonsai trees work, with or without upgrades

### ISSUE THREAD

**Issue by CritFlaw** [thraaawn/BonsaiTrees#283]
Not even something simple like oak + dirt drops anything, the manual chop button does not work. Tree grows to full percent and neither a hopper or axe upgrade changes anything, manual chop button does not work, just goes to 100% and stops. 

Redstone button restarts the cycle but still makes it stop at 100%

Forge: 1.18.2 - 40.0.48
Bonsai Trees: bonsaitrees3-3.1.0.jar

**Comment by violetkitty87** [comment]
Im playing a pack with a few friends that we updated recently to 1.18.2 and were having the exact same issue

**Comment by UdoMorgenstern** [comment]
sadly this issue turns this mod into a decoration only mod. 
confirmed using: 
1.18.2 - 40.1.0
bonsaitrees3-3.1.0.jar
libnonymous-2.1.0.jar

**Comment by UdoMorgenstern** [comment]
oddly sometimes they are working (after a server restart) - to be determined if this was a one time glitch or if this is reproducible

**Comment by grimgrinninjay** [comment]
We have been experiencing the same thing, however, restarting the server and clients has fixed it for us every time.

**Comment by AbsolemJackdaw** [comment]
issue has been resolved in merged PR:
https://github.com/thraaawn/BonsaiTrees/pull/305

**Comment by davenonymous** [comment]
If you have the time to re-test this issue with the [latest version](https://www.curseforge.com/minecraft/mc-mods/bonsai-trees/files/5632262), it would be greatly appreciated.
