### ISSUE TITLE
Bug: Wrong ModId

### ISSUE THREAD

**Issue by Samtrion** [thraaawn/BonsaiTrees#29]
https://github.com/thraaawn/BonsaiTrees/blob/a0f174c5ba6a5cc0c82b889b3324e26a29f7bef9/src/main/java/org/dave/bonsaitrees/compat/TheOneProbe/TopCompatibility.java#L42

I think here you have the wrong mod id.

**Comment by thraaawn** [comment]
Fixed in 1.0.2
