### ISSUE TITLE
insert axes 

### ISSUE THREAD

**Issue by trechetican** [thraaawn/BonsaiTrees#295]
this may not be an issue, this could be by design. but i cannot seem to be able to insert an axe using a pipe system or hopper.
using the latest version 3.1.0

**Comment by milkev** [comment]
I also cannot insert axes via any io. This is really annoying right now as the axes take durability damage, with no way to automatically resupply them, you cant have the bonsai run infinitely without manual work or an unbreakable axe.

Also on 3.1.0, using atm7 on a dedicated server.

**Comment by milkev** [comment]
it seems integrated dynamics can insert via right clicking with the player simulator, is kind of a complex solution to something that should be fairly simple though

**Comment by milkev** [comment]
integrated dynamics doesnt even work all the time though, the same settup works on some of my bonsai pots, but not others

**Comment by davenonymous** [comment]
It is possible to insert axes and other upgrades from the top side of the block.
