### ISSUE TITLE
Tree stops growing when put more than 2 Apotheosis max enchant levels of Efficiency book(more than 5 lvl) in the bonsai pot

### ISSUE THREAD

**Issue by tankyap** [thraaawn/BonsaiTrees#297]
Forge version:40.1.48
Mod version: 3.1.0 (1.18.2)

So I just found a ridiculous and broken issue while putting more than 2 Efficiency book with the max enchant lvl from [Apotheosis](https://www.curseforge.com/minecraft/mc-mods/apotheosis) mod that let you have more enchant levels on the books. It is a little bit confusing and complicated, but I'll try my best to complain about his issue.

  After putting two modded books into it, the tree stops at 0% and the tree model starts overgrown for some reason.And also that you can spam click the axe to collect the resources even its not at 100% grown, and it also cannot auto-chopping the tree even having the auto-cut upgrade in the bonsai pot.

Heres the image of while putting between vanilla max enchant level or Apotheosis mod max enchant level of Efficiency book in it.

The bonsai inventory screen and the tree model looking image while putting 4 vanilla Efficiency book in the bonsai pot:
![2022-06-09_04 24 57](https://user-images.githubusercontent.com/87649059/172788159-b4e72aea-4846-4b67-9e46-f624508897a3.png)
![2022-06-09_04 25 00](https://user-images.githubusercontent.com/87649059/172788169-85fe19ba-7a33-4bdb-8cd2-dc2f674f7744.png)

And here is the another 2 image that is same as the vanilla but with modded enchant level of Efficiency in it:
![2022-06-09_04 25 07](https://user-images.githubusercontent.com/87649059/172788617-aa3aa6c6-f488-478b-9695-429268e7981d.png)
![2022-06-09_04 26 02](https://user-images.githubusercontent.com/87649059/172788632-2c729484-7b0f-4489-90ea-dd0aecf06dc3.png)

At the end, I just hope that this mod supports more enchant levels to make it working 

And the game lags a lot when plant some chorus trees, it remains 20 FPS on average when I was near the chorus tree. Hope that it can optimized a little bit

**Comment by Nevrai** [comment]
I second this. Would love to have Apotheosis support!

**Comment by davenonymous** [comment]
There were some issues with efficiency upgrades and rendering that should be fixed in the 1.20.1 version of the mod.
