### ISSUE TITLE
[1.18.2] Please add support for Oh the Biomes you´ll go

### ISSUE THREAD

**Issue by lifeNerd** [thraaawn/BonsaiTrees#298]
Oh the Biomes you´ll go has a bunch of trees that arent supported yet.
https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go

and please add forge:cherry as fruit for both cherrytrees (a.g. croptopia has cherrys and has a conversion from croptopia:cherry to forge:cherry)

**Comment by MCBEModder2020** [comment]
good idea

**Comment by Bandasha** [comment]
I wrote a whole lot of .json files for the byg saplings. Some drops and soils may need amending though.

I also can't figure out how to make a pull request to upload the files - any help appreciated. If I can email or google drive them to someone more knowledgeable than myself that would be amazing.

**Comment by nightmare3007** [comment]
i have made my own file here in here [https://github.com/thraaawn/BonsaiTrees/issues/311](url) if you want to builds it or use it as resource pact
and if you dont want to do that you  can have the finish jar file 
[modid-OreTree-1.18.2-0.2.5.10.jar.zip](https://github.com/thraaawn/BonsaiTrees/files/9428063/modid-OreTree-1.18.2-0.2.5.10.jar.zip)
just un zip it to get the jar file
also this is my oretree mod jar that i moded [i am not the author] myslef and add many tree to it.
