### ISSUE TITLE
Variable Soil, i.e. some trees can only grow on specific soil

### ISSUE THREAD

**Issue by thraaawn** [thraaawn/BonsaiTrees#3]
Currently the soil in Bonsai Pots is fixed and hard-textured to dirt.
We should probably add support for other soils, e.g. for Tinkers Construct Slime Trees that can only grow on slimy grass.

Not sure about this because of the increased complexity.

**Comment by BryanBoru** [comment]
would seem less complex if the recipe would be made with the specific soil in the recipe (slimy soil or netherrack in place of soil etc.)
