### ISSUE TITLE
How do hopping Bonsai pots work with full inventories?

### ISSUE THREAD

**Issue by CDArena** [thraaawn/BonsaiTrees#30]
Place a pot on a chest and plant a sapling. What happens when the chest is full? What happens if the chest is pre "filtered" by filling each slot with a stick? Does the pot have an internal inventory, and does it have a limit, or will it just save items until it crashes java?

**Comment by Samtrion** [comment]
It will first be simulated if the inventory can accept the drops. If one or more drops can't be placed inside the inventory, the process will be suspended until all drops can be inserted into the inventory.

https://github.com/thraaawn/BonsaiTrees/blob/a0f174c5ba6a5cc0c82b889b3324e26a29f7bef9/src/main/java/org/dave/bonsaitrees/tile/TileBonsaiPot.java#L212-L217

**Comment by CDArena** [comment]
Cool - thanks! Sounds very safe - thanks!
