### ISSUE TITLE
Add support for soil based on textures instead of blocks

### ISSUE THREAD

**Issue by YassaaaTU** [thraaawn/BonsaiTrees#300]
Modloader : Forge 40.1.51
MC Version : 1.18.2
Bonsai Trees 3 : 3.1.0
lib : 2.1.0
_________

_I am also using a forge port of sodium called rubidium I don't know if it has anything to do with the custom soil not rendering._

Adding custom soil (in my case I am using Mysticalagriculture farmland) doesn't seem to render:
![bonsaitrees3](https://user-images.githubusercontent.com/5587106/174307888-329cd84e-be23-473e-bdd8-c89f7c41d86f.png)

The json file for the custom soil looks like this:

![image](https://user-images.githubusercontent.com/5587106/174308175-3a2c1d8a-9a7a-44d7-8600-eb5d498edede.png)

I'm using kubejs to load it the file path is 
`[...]\curseforge\minecraft\Instances\justforfun\kubejs\data\bonsaitrees3\recipes\soil\mysticalagriculture`

**Comment by nightmare3007** [comment]
i have some of that problem.
but i notes it in mysticalagriculture soil as other like my oretree soil is working fine.
see here
![image](https://user-images.githubusercontent.com/68788826/186765516-63df6365-2b9d-4b05-a052-aaf4980c0f86.png)
as for mysticalagriculture soil i change the display soil to block from Minecraft and other mod
see here 
![image](https://user-images.githubusercontent.com/68788826/186765705-df76c930-b779-4ede-916f-a1198617d0f0.png)

**Comment by nightmare3007** [comment]
here is my file for comparison if you want.
![image](https://user-images.githubusercontent.com/68788826/186766003-5af00544-e22f-4775-b446-2ea8b0606eb1.png)

**Comment by davenonymous** [comment]
This probably due to some blocks not being simple full sized-blocks or even with custom block entity renderers.
I will investigate and see what I can do.
Probably simply allowing to specify the texture to be used for the soil instead of the block.
