### ISSUE TITLE
same craft

### ISSUE THREAD

**Issue by Arnyet** [thraaawn/BonsaiTrees#301]
I apologize for my lousy English, it's not my native language.

I have a big problem (Terraqueous mod has the same craft) regarding an item (bucket and plot) they are the same craft, 5 bricks,

and the same position on my craft table (I report the feedback to both Owner )

I apologize for the inconvenience, an apology and many thanks in advance. have a nice day.

**Comment by YassaaaTU** [comment]
use polymorph or change the recipes using the kubejs mod or use a datapack to change the recipes 
but I recommend [polymorph](https://www.curseforge.com/minecraft/mc-mods/polymorph)

**Comment by Arnyet** [comment]
> use polymorph or change the recipes using the kubejs mod or use a datapack to change the recipes but I recommend [polymorph](https://www.curseforge.com/minecraft/mc-mods/polymorph)

Thank you very much for your answer, I will try it. Thank you very much

**Comment by MCBEModder2020** [comment]
yes, polymorph is a very good mod but crafttweaker is also an option
