### ISSUE TITLE
Unnecessary waste of performance on recipe search

### ISSUE THREAD

**Issue by twothe** [thraaawn/BonsaiTrees#302]
While analyzing performance of my server I learned that BT3 constantly searches through the recipes [to figure out what to generate](https://github.com/thraaawn/BonsaiTrees/blob/cf166b3beb9567e987a9a89f61f1611bcf9f6b7b/src/main/java/com/davenonymous/bonsaitrees3/blocks/BonsaiPotBlockEntity.java#L241).

While this is not a problem on smaller modpacks it becomes a significant loss of performance on larger modpacks like ATM7.

Instead of querying the recipe every single tick it would be sufficient to figure that out once the current growth time has ended and/or the sapling slot has changed. Worst time - if any mod somehow changed recipes, it will waste one growth time, while at the same time the CPU time will go down to almost nothing. Even better solution would be to just cache the recipes locally, as there are usually not that many saplings that are processed.

**Comment by Sixdd6** [comment]
Dear god yes please fix this, I'm working on a modpack that includes over 300 mods and it wasn't till I finally got into mass testing that I realized that this was a problem. I know, begging doesn't get us anywhere, just wanted to make sure it is known that this is still an issue.

**Comment by davenonymous** [comment]
If you have the time to re-test this issue with the [latest version](https://www.curseforge.com/minecraft/mc-mods/bonsai-trees/files/5632262), it would be greatly appreciated.
