### ISSUE TITLE
bonsai growth time

### ISSUE THREAD

**Issue by mlsundro** [thraaawn/BonsaiTrees#306]
Hi, would it be difficult to add an option in the config to decide how long it takes for the trees to grow and be ready to harvest? I would like for it to take a LOT longer than the few seconds it currently takes, as it would be fun to see it slowly grow over a few minecraft days.
Or maybe there's a relatively simple way I can do it myself? I do have some fundamental coding knowledge as long as I'm pointed in the right direction.

**Comment by davenonymous** [comment]
There is the `minimumRequiredTicks` config option, but that would set the growth time for all trees.
Adding a global `requiredTicksModifier` option seems reasonable though, i.e. a simple multiplier for that value.
