### ISSUE TITLE
Bonsai growing at a negative rate potentially causing massive amounts of loot to be produced

### ISSUE THREAD

**Issue by Primalinea** [thraaawn/BonsaiTrees#310]
Video showcasing the bug:
https://www.youtube.com/watch?v=9HdThzw5iOQ

Also, the tree can become infinitely big causing fps drops when loaded

Image of a bonsai pot placed at the build limit after 10 minutes:
![2022-08-18_05 37 19](https://user-images.githubusercontent.com/111784460/185984163-38db0e9e-69ca-4066-ab20-7716b9ca5b58.png)

PS:this is extremely funny

**Comment by Nessiesson** [comment]
yeah it's great!
![Screenshot_20220823_030753](https://user-images.githubusercontent.com/1357875/186046126-65ad2649-a34d-4202-9abf-5851f8ce7bfb.png)

**Comment by Primalinea** [comment]
LMAO WHAT

**Comment by davenonymous** [comment]
I'm sad to say that this should be fixed now.
