### ISSUE TITLE
[Question] Invisible growing status

### ISSUE THREAD

**Issue by wantedkeks** [thraaawn/BonsaiTrees#314]
Hej there,
I would like to achieve your knowledge and thoughts.

Background story:
For a little group of people, I created an own modpack on 1.12.2. In fact that most of them have old potato hardware, I used the modpack "Boosted FPS" by GamerPotation ( [Curseforge Link](https://www.curseforge.com/minecraft/modpacks/boosted-fps-forge) ), modpack version 1.12.2-0.1.

My purpose:
Playing with those fps mods, the behaviour of plants in the bonsaipots are going weird.
At first, there haven't been any visible plants. I could cleared it during a config edit of Tiquality.
Now, growing trees/saplings are visible and growing again.

On the other hand, other plants like sugar canes aren't visible growing/not visible. I only see the grown percentage by the one probe (or any other like waila). I hoped that everything would be growing again..

I know that it is not an issue of bonsaitrees, instead it is one of those performance mods. Unforunately, i dont know how to change that. 
Does anyone have an idea?

![image](https://user-images.githubusercontent.com/43499536/188319840-d86d8de2-0111-4c18-af21-95ba25993141.png)

At last, which version has implented the gui interface to the pots? 
Greetings and thanks for advice!

**Comment by davenonymous** [comment]
Sorry for the late answer and not being sure how to help you with this.
Weird that it breaks since it's a simple matrix transform to scale the model to the appropriate size.
Probably some kind of desync issue?

I think Bonsai Trees 3 added the GUI interface. I'd like to get rid of it again in Bonsai Trees 4 though.
