### ISSUE TITLE
Bonsai Trees 3

### ISSUE THREAD

**Issue by mcflathead05** [thraaawn/BonsaiTrees#316]
The mod is not loading correctly.

All I see is the "Bonsai Pot" but I don't see the Hoppered Bonsai Pot. I downloaded the version: [bonsaitrees3-3.1.0.jar](https://www.curseforge.com/minecraft/mc-mods/bonsai-trees/files/3677571).

I'm using Forge version: 40.1.70

Please help...

Thank you.

James
![Bonsai Pots]

(https://user-images.githubusercontent.com/75158080/191877052-e572a8fb-5468-4b63-8935-2d07d9a8f0a8.jpg)

**Comment by zerofusion04863** [comment]
im having the exact same issue if you found a way to get it in your game please let me know

**Comment by XRATEDREFLEX** [comment]
i believe you have to put a hopper in the gui on the bonsai pot
