### ISSUE TITLE
Compatibility request: Pokecube AIO [1.18.2]

### ISSUE THREAD

**Issue by xFirefalconx** [thraaawn/BonsaiTrees#317]
Hi!
I wanted to ask if it's possible to use the tree-growing berries from pokecube aio in this mod as well. They have a berry bush stage at first but then mature in a fully grown tree and while it's quite realistic I would love to have little ones I can harvest instead. I found this mod by chance and hope it's possible to implement such a feature to make this possible.
If it's already working - just let me know and close this please! 
Thanks in advance.

**Comment by davenonymous** [comment]
This is possible with custom data/resource packs.
You can read up on how to add custom trees to the mod (in the readme of the repository) and create a pull request for integration in the mod itself.
