### ISSUE TITLE
[Suggestion] Tree Whitelist

### ISSUE THREAD

**Issue by Xaikii** [thraaawn/BonsaiTrees#32]
Title says it all ^^'

besically I dont want to enable the BonsaiTree for every Tree ^^'

**Comment by thraaawn** [comment]
You already can, it's a bit more complicated than a simple whitelist.
See the relevant [readme section](https://github.com/thraaawn/BonsaiTrees#sapling-compatibility) for details.
Pull Requests are welcome!
