### ISSUE TITLE
Bonsai Trees 3 not working correctly in skyfactory 4

### ISSUE THREAD

**Issue by zerofusion04863** [thraaawn/BonsaiTrees#327]
Bonsai Trees 3

when i go into the game it shows the one bonsai pot and nothing else like the hopping bonsai and I've tried to reinstall the pack but i cant seem to get it to work i would greatly apricate some help with this thank u also im trying everything i can but nothing shows up thank u

**Comment by RoyalReject** [comment]
You upgrade it by putting specific items into the GUI

**Comment by jstansel** [comment]
Skyfactory 4 was for MC 1.12.2. I can't figure out how you installed Bonsai Trees 3 with it.
