### ISSUE TITLE
Bonsai Pot Block Entitiy loads Client class

### ISSUE THREAD

**Issue by Tschipp** [thraaawn/BonsaiTrees#329]
Related issue: https://github.com/Tschipp/CarryOn/issues/369

Carry on calls the BlockEntity#load function on the server side, which then classloads BonsaiPotBlockEntity.
BonsaiPotBlockEntity imports ClientLevel here: https://github.com/thraaawn/BonsaiTrees/blob/1.18.1/src/main/java/com/davenonymous/bonsaitrees3/blocks/BonsaiPotBlockEntity.java#L14

Instead of checking for ClientLevel, do `level.isClientSide` instead.
I will add safeguards on carry on's side to prevent duplication of carried blocks.

**Comment by davenonymous** [comment]
This should be fixed in the latest versions for 1.18.2, 1.19.2 and 1.20.1.
If you wouldn't mind retesting, that'd be very much appreciated.
