### ISSUE TITLE
Hopping Bonsai Pot cause severe lag in SkyFactory4

### ISSUE THREAD

**Issue by AsTupIdymaNer** [thraaawn/BonsaiTrees#330]
We played SkyFactory4 and suffered a severe lag. I used spark for performance analysis. Here is the report. 
https://spark.lucko.me/sHH8pwHTBN
The process updateHoppingExport cause the lag.Why and how could I do to solve the problem.
thank u!

**Comment by davenonymous** [comment]
If you have the time to re-test this issue with the [latest version](https://www.curseforge.com/minecraft/mc-mods/bonsai-trees/files/5632262), it would be greatly appreciated.
