### ISSUE TITLE
Mod unable to load on 1.20.1

### ISSUE THREAD

**Issue by LeafyLethal** [thraaawn/BonsaiTrees#337]
I keep getting the startup error: `Mod File needs language provider javafml:47.3 or above to load. We have found 47.` 
I opened my latest.log and found this line: `[08:52:35] [main/ERROR]: Missing language javafml version [47.3,) wanted by BonsaiTrees3-1.20.1-3.3.0.jar, found 47`
I'm playing Minecraft 1.20.1 and I'm using BonsaiTrees3-1.20.1-3.3.0.jar
Is there a way to fix this error?

**Comment by davenonymous** [comment]
Already fixed on github. I'll push a new release later today.
