### ISSUE TITLE
Saplings won't plant in either bonsai base

### ISSUE THREAD

**Issue by BigAl607** [thraaawn/BonsaiTrees#36]
**Bonsai Trees version**: 1.0.2-b63
**Forge version**: 14.23.2.2618
**I am not using Optifine**: I am not
**Link to Crashlog**: Not getting a crashlog
**Screenshot (if possible)**: n/a

**Description of the problem including expected versus actual behavior:**

Tried both left clicking and right clicking, and shift+rt & shift+lt clicking saplings on both of the bonsai bases, and neither would accept a sapling.

**Comment by thraaawn** [comment]
I will look into it when I get home from work.
What other mods are you running? Do you maybe have some skill-restriction mod or something else that might be preventing block interactions with bonsai pots?

**Comment by jamzam90** [comment]
I too have this problem, however it is in modern skyblock 3 departed. Version 1.0.2-b63

**Comment by thraaawn** [comment]
Did you try both off- and main-hand?

**Comment by corruptedfiend** [comment]
I am having the same problem, unable to plant it on either the normal or hopper version. I was able to on my single player world, but I am unable to on a server. Playing version 3.1.5 and kitchen sink mode. I've also tried multiple saplings, vanilla and modded.

**Comment by thraaawn** [comment]
This is fixed in version 1.0.3 of the mod.
