### ISSUE TITLE
The bonsai pot's getCapability method always returns the handler, even if the given capability is of a different type.

### ISSUE THREAD

**Issue by AlexIIL** [thraaawn/BonsaiTrees#37]
Specifically that [the bonsai pot tile entitty's `getCapability` method](https://github.com/thraaawn/BonsaiTrees/blob/master/src/main/java/org/dave/bonsaitrees/tile/TileBonsaiPot.java#L259) just casts the handler to T, and returns it. However the [forge javadoc](https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/common/capabilities/ICapabilityProvider.java#L54) states that it should `Returns null when {@link #hasCapability(Capability, EnumFacing)} would return false.` You could probably fix this by changing the method to:
````java
@Override
public <T> T getCapability(Capability<T> capability, EnumFacing facing) {
    if (hasCapability(capability, facing) {
        // For some reason forge does an unchecked cast in here, and pretends that it doesn't matter.
        return capability.cast(handler);
    }
    return null;
}
````

(Reported in https://github.com/BuildCraft/BuildCraft/issues/4061)

**Comment by thraaawn** [comment]
Hey thanks for the report!
