### ISSUE TITLE
Bonsai Tree Crashes 

### ISSUE THREAD

**Issue by Sacrificialgaming** [thraaawn/BonsaiTrees#39]
Crash as soon as you launch the game

**Bonsai Trees version**: 1.0.4-b71
**Forge version**: 14.23.3.2702
**Crash** https://gist.github.com/Sacrificialgaming/d81d10aed1f3974a0820e296d0e1c792

**Comment by thraaawn** [comment]
In the future please don't shorten/ignore the issue template, thank you.
Looks like this happens when the forestry arboriculture module is disabled.
I will look into it.
