### ISSUE TITLE
Screenflicker with optifine

### ISSUE THREAD

**Issue by JasonKillsUs** [thraaawn/BonsaiTrees#4]
Hello after i planted the first Bonsai Tree my screen started to flicker like crazy, hard to describe...looks like a quick switch between antialising off/on. No crash nothing in the log file. I took the mod out and everything seems to be okay.
Is the mod optifine compatible?

**Comment by thraaawn** [comment]
Not "officially" supporting optifine. If it works, great. If it does not: ¯\_(ツ)_/¯ 
Please take out optifine and see if that helps. Optifine more often than not breaks mods and as such you'll rarely find a mod actively supporting it.

If this issue still persist after you've removed optifine, please reopen a new ticket.
