### ISSUE TITLE
[BUG] Cannnot save Thaumcraft Silverwood tree

### ISSUE THREAD

**Issue by hron84** [thraaawn/BonsaiTrees#40]
**Read then remove this section**:
Please read [this](https://vazkii.us/br101/) and follow there instructions in there before creating an issue.
Most importantly, do not create an issue if you have not tried fixing it by using the latest version of the mod!

Also make sure you've read the full readme [here](https://github.com/thraaawn/BonsaiTrees/blob/master/README.md) on github.

**Bonsai Trees version**: 1.0.4-b71
**Forge version**: 2673
**I am not using Optifine**: `true`
**Link to Crashlog**: [here](https://gist.github.com/hron84/348b007e4d00dd21b69235a3344e7841)  (not an actual crashlog, the game goes toward)

**Description of the problem including expected versus actual behavior:** `/bonsaitrees saveTreeShape thaumcraft:silverwood` dropped this.

**Comment by thraaawn** [comment]
Hey, I'm currently in the process of rewriting the shape format, including this command. That should fix it.
Until then and if you're only after thaumcrafts trees you could use the already committed, but unreleased json files in this repository:

Types
- [Greatwood](https://raw.githubusercontent.com/thraaawn/BonsaiTrees/master/src/main/resources/assets/bonsaitrees/config/types.d/thaumcraft_greatwood.json)
- [Silverwood](https://raw.githubusercontent.com/thraaawn/BonsaiTrees/master/src/main/resources/assets/bonsaitrees/config/types.d/thaumcraft_silverwood.json)

Shapes
- Greatwood [1](https://raw.githubusercontent.com/thraaawn/BonsaiTrees/master/src/main/resources/assets/bonsaitrees/config/shapes.d/thaumcraft_greatwood001.json) [2](https://raw.githubusercontent.com/thraaawn/BonsaiTrees/master/src/main/resources/assets/bonsaitrees/config/shapes.d/thaumcraft_greatwood002.json) [3](https://raw.githubusercontent.com/thraaawn/BonsaiTrees/master/src/main/resources/assets/bonsaitrees/config/shapes.d/thaumcraft_greatwood003.json)
- Silverwood [1](https://raw.githubusercontent.com/thraaawn/BonsaiTrees/master/src/main/resources/assets/bonsaitrees/config/shapes.d/thaumcraft_silverwood001.json) [2](https://raw.githubusercontent.com/thraaawn/BonsaiTrees/master/src/main/resources/assets/bonsaitrees/config/shapes.d/thaumcraft_silverwood002.json) [3](https://raw.githubusercontent.com/thraaawn/BonsaiTrees/master/src/main/resources/assets/bonsaitrees/config/shapes.d/thaumcraft_silverwood003.json)

**Comment by hron84** [comment]
Thank you very much! I was only needed Thaumcraft trees because I plan to use a lot of them later for my wizardry tower and I wanted to start producing woods as early as I can because Thaumcraft trees does not respond to bonemeal.

**Comment by hron84** [comment]
@thraaawn Update: I installed the files you provided, but does not work. Neither JEI shows the possibility, nor the saplings cannot planted on a hopping bonsai pot. Please help.

**Comment by thraaawn** [comment]
Thaumcraft support has been released in v1.0.5
