### ISSUE TITLE
[Enhancement Suggestion] Stopping animation once tree is grown

### ISSUE THREAD

**Issue by TheGuyFromTheInternet** [thraaawn/BonsaiTrees#5]
For fruit bearing trees like in Pam's harvestcraft, I think it would be aesthetically beneficial if there would be an option to stop the animation of tree growing in a cycle. This can be applied to all the trees in the "hopper-pot" since it auto-harvests.

**Comment by thraaawn** [comment]
This would increase complexity a lot, especially since it would need to be data driven.
I *might* add something like this at a later point, but not currently.
