### ISSUE TITLE
[Suggestion] Artificial Light Source/Modifier bonus

### ISSUE THREAD

**Issue by drakray** [thraaawn/BonsaiTrees#57]
A block, that placed [config]max block over a Bonsai Pot, could act as a Light Source(replacing the need to have Sky View), and/or a Bonus modifier to growth/drop, like Greenhouse block from ActuallyAdditions.

Maybe even both, a Lamp over a Glass over a Pot, for maximum indoor microFarming! :D

Could be added via CraftTweaker for packmaker, that would be nice I think.

**Comment by thraaawn** [comment]
I've just added soils that can give bonuses and that can be fully tweaked with json files and crafttweaker.
Maybe I'll add a light source of some kind sometime in the future, but don't expect this anytime soon.
It might not happen at all.
