### ISSUE TITLE
[Suggestion] About CraftTweaker integration

### ISSUE THREAD

**Issue by drakray** [thraaawn/BonsaiTrees#58]
Could it be possible to change string to ItemStack? as it would add support for metadata/blockstate.
As of now, I don't think it's possible to specify meta/state to differentiate block, like multiple BoP grass type and such.

Or maybe just add a variable to Soil function for metadata. if that's simpler.

**Comment by thraaawn** [comment]
I'm not sure where you want to use an ItemStack instead of a String. I'm also not sure what part does not support metadata.
CraftTweaker can not be used to add new Soils, you are supposed to do that using json files.

Please elaborate a bit.

**Comment by drakray** [comment]
Ah, that's the part I missed lol, I tried to add soil directly with CT using block name lol.
Could it be eventually possible though to add soil with CT using ItemStack?
JSON is fine and all, but CT is very simple, specially for those who use it regularly.

**Comment by drakray** [comment]
Maybe one question: can there be more than one definition in a JSON file? Or must I make 1 file per block/meta?

**Comment by thraaawn** [comment]
Yes, you can. See [greenSlime.json](https://github.com/thraaawn/BonsaiTrees/blob/master/src/main/resources/assets/bonsaitrees/config/soils.d/greenSlime.json).
