### ISSUE TITLE
Bonsai Trees Tick time issues

### ISSUE THREAD

**Issue by Darkere** [thraaawn/BonsaiTrees#61]
I like using bonsai trees however the tick time on them is very severe.
My basic bonsai oak tree takes 0.6ms of server tick time. Someone else had even more severe issues with up to 5ms per tree. 
This seems like a bug to me as other than graphics the only thing it does is produce an item every few seconds.

**Bonsai Trees version**: b117
**Forge version**:2760
**Screenshot **: [here](https://imgur.com/a/NcRhBuA)

**Comment by AdaraChristine** [comment]
This is very hard on servers. I too do not want to remove it from Mystical Village but i may have no choice.

**Comment by thraaawn** [comment]
I assume those barrels only accept one type of item?
That's a bug and actually allows abuse of bonsai trees to increase the chance to get a specific drop. While also increasing tick time.

**Comment by thraaawn** [comment]
That's weird. What he says and what the screenshot is saying are two different things. Trees on Hopping Pots only stop at 100% if they can't drop their loot into the inventory below. All three trees in the screenshot are at 100%, but are not being auto-harvested. Is he sure the inventory below is empty or rather has room for all items that should get dropped?

**Comment by Darkere** [comment]
Yeah.. well regardless the tick time is high anyway.

I tested with the new version. In the pack (ATM3:Remix) there are no improvements.
https://i.imgur.com/FebpWnZ.png

But in my testpack that only has Actually Additions and Bonsai trees installed.
https://i.imgur.com/bBdwHHx.png

So it's a compatibility issue. I'm gonna check tinkers next.

**Comment by Yamza** [comment]
It's not just the Hopping Bonsai that has tick issues, even the normal one does. 

This is the normal pot while growing
`[16:18:13] [main/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] 783 micro-s/t: TILE_ENTITY: {WORLD_ID=0, BLOCK_NAME=TileBonsaiPot, BLOCK_POS_X=-360, BLOCK_POS_Y=44, BLOCK_POS_Z=229, BLOCK_CLASS_NAME=org.dave.bonsaitrees.tile.TileBonsaiPot, NANOS=828074826}`

This is the normal pot idle (after it's grown)
`[16:23:30] [main/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] 555 micro-s/t: TILE_ENTITY: {WORLD_ID=0, BLOCK_NAME=TileBonsaiPot, BLOCK_POS_X=-360, BLOCK_POS_Y=44, BLOCK_POS_Z=229, BLOCK_CLASS_NAME=org.dave.bonsaitrees.tile.TileBonsaiPot, NANOS=596604433}`

**Comment by thraaawn** [comment]
Sorry, did not have time to look into this further.
I did not forget, though. Still on my todo list.

**Comment by thraaawn** [comment]
Does the latest build 130 from [here](https://www.dropbox.com/sh/7yyd9dgii1epibu/AADARWLwgjOBu9wU-zZVHp-ra?dl=0) fix it? With the included fix a lot of the lookups that are happening when growing a tree are now being cached and only done once when the world is loaded or a sapling being planted.

**Comment by Darkere** [comment]
Well congrats that seems to have fixed it. 

![image](https://user-images.githubusercontent.com/4283717/46904646-d6b8c280-cee7-11e8-977d-2d754841e8c4.png)

Thank you very much.

**Comment by thraaawn** [comment]
Excellent! Thanks for the retest. Will release a new version on curse before the weekend is over.
Cheers!
