### ISSUE TITLE
/bonsaitrees generateMissingShapes yes

### ISSUE THREAD

**Issue by raziel23x** [thraaawn/BonsaiTrees#63]
**Bonsai Trees version**: bonsaitrees-1.0.5-b77.jar
**Forge version**: 2760
**I am not using Optifine**:not install

**Description of the problem including expected versus actual behavior:**
I have cheats enabled and i can switch between creative and survival but when i use 
  /bonsaitrees generateMissingShapes yes
I get the message i do not have permission to use this command

**Comment by thraaawn** [comment]
You need to have the permission to send server commands, i.e. be an Operator.

**Comment by raziel23x** [comment]
How do you give OP settings in a Single player game then tell me this

**Comment by raziel23x** [comment]
Okay i went into the Single player world and typed /op and i get the message this is not a unknown command so nope cant do this command in a single player game and why would i need to have to have the permission to send server commands, i.e. be an Operator in a single player game which i am using to do the command in
