### ISSUE TITLE
Unable to plant saplings while torches in off-hand

### ISSUE THREAD

**Issue by mcsoapthgr8** [thraaawn/BonsaiTrees#64]
**Bonsai Trees version**: 1.0.5-b77
**Forge version**: 14.23.4.2760
**I am not using Optifine**: not using Optifine
**Link to Crashlog**: not reporting a crash
**Screenshot (if possible)**: n/a

1. Place bonsai pot in world
2. Put torches in off-hand
3. Select compatible sapling in main hand
4. Right click sapling into bonsai pot

Expected: Sapling to be planted
Actual: Sapling not planted until I remove torches from off-hand
Additional Note: Sapling is planted if sticks or cobblestone are in off-hand

**Comment by thraaawn** [comment]
> Most importantly, do not create an issue if you have not tried fixing it by using the latest version of the mod!
