### ISSUE TITLE
[Enhancement] Compatibility Suggestions

### ISSUE THREAD

**Issue by ghost** [thraaawn/BonsaiTrees#70]
Even tho some of these can be added manually, It would help out a lot with modpacks.

- Twilight Forest Support
- Extra Planet trees - This would be used for people who use this mod like us.
- Animus Tree Support for the Blood Sapling.
- Natura Nether Trees

Thanks for taking your time to read it this,
Flame
-

**Comment by hron84** [comment]
See #22
