### ISSUE TITLE
Sapling in off-hand not placed when main hand has item

### ISSUE THREAD

**Issue by mcsoapthgr8** [thraaawn/BonsaiTrees#71]
**Bonsai Trees version**: 1.1.0-b117
**Forge version**: 14.23.5.2769
**I am not using Optifine**: not using optifine
**Link to Crashlog**: N/A
**Screenshot (if possible)**: N/A

1. Place down bonsai pot (regular or hopping)
2. Place dirt in bonsai pot
3. Put any sapling in off-hand
4. Select any item that is neither a sapling nor a dye in main-hand
5. Right-click onto bonsai pot

Expected: Sapling in off-hand to be placed into bonsai pot
Actual: Sapling was not placed into bonsai pot

**Comment by thraaawn** [comment]
Hmm. You are right. This should definitely work.
The code handling this on my end needs to be reworked, since this is a bit more complicated than first assumed. I will look into it at some point, but not for the this next release.

I have to ask for patience, sorry.

**Comment by mcsoapthgr8** [comment]
Not a problem - there's an easy workaround - just put the sapling in the main hand :-)
