### ISSUE TITLE
"Missing" configurations or configurations not accessed from default

### ISSUE THREAD

**Issue by duely** [thraaawn/BonsaiTrees#75]
**Read then remove this section**:
Please read [this](https://vazkii.us/br101/) and follow there instructions in there before creating an issue.
Most importantly, do not create an issue if you have not tried fixing it by using the latest version of the mod!

Also make sure you've read the full readme [here](https://github.com/thraaawn/BonsaiTrees/blob/master/README.md) on github.

**Bonsai Trees version**: b117, current branch.
**Forge version**: 2750, 2701
**I am not using Optifine**: No Optifine here!
**Link to Crashlog**: Crash log not quite relevant, see details.
**Screenshot (if possible)**: Not relevant.

**Description of the problem including expected versus actual behavior:** Having updated my modpack to the most recent version available on CurseForge (b117), I was surprised when dirt failed to render properly in trays. I seemed to be able to place soil into the tray and plant a tree on it, but the rendering issue was bizarre.

I switched to the most recent beta build available on Travis and found I had the same problem.

**Steps to reproduce:** I created a clean checkout of Bonsai Trees, setupDecompWorkspace and then launched a debug through a gradle runClient in IntelliJ with a deobfuscated recent version of TwilightForest. While attempting to place soil/saplings into the pot I actually incurred a complete crash: https://gist.github.com/duely/58fea8ae87df03fa00904f1c9aa98126

Investigating this crash, it appeared as though the soil registry was empty. I checked the run/config/bonsaitrees/soils.d folder and found it empty, but presumed that it would be accessing the defaults found in the assets. Again, I'm relatively new to modding Minecraft, so I'm not 100% sure how this situation works.

I was able to rectify the issue (and cause soils to one again render in pots) by copying the configurations from the assets folder into the run/config folder. I'm not sure if this is the intended solution, but it seems to work for now.

**Comment by thraaawn** [comment]
I can not reproduce this. Works in dev and normal environments from both assets as well as config folders.

**Comment by duely** [comment]
Disregard then, there must've been something weird that I did with the checkout or with Eclipse.
