### ISSUE TITLE
[Config Request] Speed of Growth

### ISSUE THREAD

**Issue by Boolyman** [thraaawn/BonsaiTrees#8]
Is there any way you can add a config option to adjust the speed at which a tree completes a growth cycle?  It seems very fast right now, for the purposes of my pack at least.

**Comment by thraaawn** [comment]
There is no global modifier for the growtime (yet), but you can configure the json based trees individually.
I'll add that global modifier and a CraftTweaker method for non-json trees.

Would that work for you?

**Comment by Boolyman** [comment]
Does configuring the json based trees myself allow me to adjust their growth time?

**Comment by thraaawn** [comment]
Yes, it would. They have a growTimeMultiplier field. You'd simply extract the json files in the types.d folder to your config/bonsaitrees/types.d folder and overwrite/add their growTimeMultiplier field.

That has some disadvantages though. If I change the original json in the jar yours still has priority and would overwrite my changes.

At this point I'd recommend waiting a bit until I get the above mentioned features in and put out a new release. Probably sooner (i.e. today) than later (at most Sunday).

**Comment by thraaawn** [comment]
Build is uploaded to curse, it takes a moment to get approved.
Enjoy!

**Comment by Boolyman** [comment]
Awesome work!  Already tested it out and it works splendidly!  Nice job!
