### ISSUE TITLE
Excessive lag

### ISSUE THREAD

**Issue by minakitty** [thraaawn/BonsaiTrees#80]
**Read then remove this section**:

Should note the https://vazkii.us/br101 link in the template gives a 404

**Bonsai Trees version**:  1.1.1-b138
**Forge version**: 14.23.4.2768
**I am not using Optifine**: No Optifine, but do have FoamFix
**Link to Crashlog**: No crash
**Screenshot (if possible)**: [here](http://prntscr.com/lh9kxx) - screenshot is the lag from on top of an Iron Chest or a vanilla chest using LagGoggles

**Description of the problem including expected versus actual behavior:** Hopping Bonsai works as expected, creating the tree and dropping drops.  However, after the chest gets full the bonsai hopper becomes -very- laggy.  I do normally use chests from the Iron Chest mod, and they're very laggy, but even on vanilla chests they're still a source of lag.  Uncertain if this is an Iron Chest issue or if there's a preferred method for this.  For what it's worth, changing B:waitForEmptyItemBuffers to true in the server config didn't seem to make a difference, so I think that means the lag isn't directly linked to voiding or not voiding

**Steps to reproduce:** Place Bonsai Hopper on top of chest.  Fill chest with assorted junk or let hopper fill the chest on it's own.  Plant tree and wait for it to fill completely

**Comment by TyreForHyre** [comment]
This is actually a vanilla Hopper issue. You can reproduce the same effects by pointing a hopper into a full inventory and filling the hopper with multiple different types of item stacks.

**Comment by minakitty** [comment]
So, to prevent this from happening I'd have to have a mechanism to void anything that can't fit in the chest separate from what Bonsai uses?

**Comment by TyreForHyre** [comment]
Sadly yes, either you separate em out from the main inventory that the hopper is located, or use something like storage drawers where you can just slap on a void upgrade.

**Comment by i9hdkill** [comment]
@Darkere Did you test if your change somehow actually reduces the ridiculous lag?
