### ISSUE TITLE
High tick rate

### ISSUE THREAD

**Issue by MacWhinny** [thraaawn/BonsaiTrees#85]
So i'm finding that the BonsiaTrees are causing over ticking and when people have many of them it will obviously cause servers to start lagging. Thought i'd post this to let you know

I'm running 1.12.2 on the latest none recommended version of spongeforge. and it's on ATM3 Remix 1.0.1 modpack

![capture](https://user-images.githubusercontent.com/45312580/48968915-08946d00-efee-11e8-8da5-878112c914f8.PNG)

**Comment by ApolloMCC** [comment]
Hello! Bonsai pots lag the server when the output is full! 
Hopefully dev will fix this issue

**Comment by ApolloMCC** [comment]
SInce this a dead thread i will make a new one
