### ISSUE TITLE
Certain Saplings Seem to Grow Past 100%

### ISSUE THREAD

**Issue by Andr0oS** [thraaawn/BonsaiTrees#88]
**Bonsai Trees version**: 1.1.1b138
**Forge version**: release forge 14.23.5.2768
**I am not using Optifine**: No Optifine
**Screenshot (if possible)**: [here](https://imgur.com/a/Zryfj7A)

**Description of the problem including expected versus actual behavior:**
Only tested this in Modern Skyblock 3, sorry. Slime Tree Bonsai (graphically) continues to grow until it reaches a "max" size when placed on matching slimy dirt. I think it might have to do with a mismatching of the growth time for the visuals and the mechanics of the bonsai pot. Hopping Bonsai pots don't have the problem because they don't let a tree sit past 100% growth.

**Steps to reproduce:**
Place a Bonsai pot with any slimy dirt and matching slimy sapling.

**Comment by MissPotato** [comment]
Are you playing on a server or a client? 

I have a theory that maybe the config is mismatched between client and server.
