### ISSUE TITLE
Bonsai Renderer breaks signs

### ISSUE THREAD

**Issue by MissPotato** [thraaawn/BonsaiTrees#92]
**Bonsai Trees version** 1.1.2-b144
**Forge version**: 14.23.5.2815 and 14.23.5.2768
**I am not using Optifine**: No, no other mods are required. 
**Link to Crashlog**: N/A
**Screenshot (if possible)**: 
Before adding tree: https://i.imgur.com/kUfJmk9.png
After adding tree: https://i.imgur.com/LjRhusV.png
F3 Screen: https://i.imgur.com/U1qYbPw.png

**Description of the problem including expected versus actual behavior:**
Text renders solid black on signs if Bonsai pot is also being rendered, but not every sign.

**Steps to reproduce:**
I can reliably reproduce this bug with the pictured setup. Place sigs with any text surrounding a Bonsai pot (hopping or not). Place a tree in the bonsai pot, see text break. This can be reproduced with only Bonsai and Forge installed. 

 However, it always impacts other mods like Computacube when dying the turtle it'll render solid black. I removed all the mods except for the two mods and it still happened. Then later discovered the sign bug and was able to reproduce it with only Bonsai trees and no other mods.

**Comment by thraaawn** [comment]
Huh. I will look into it. Some glstate is not being reset it seems.

**Comment by MissPotato** [comment]
This picture was sent to be a user who has optifine installed along with foamfix so I don't know if this happens without it. Maybe it has something to do with this? https://i.imgur.com/vHiPfdh.jpg

**Comment by Aedda** [comment]
I'm having this issue as well. It also affects Chisels & Bits blocks causing them to shadow unexpected it. It causes the icon on Storage Drawers to mis-draw (specifically Z-fighting), and (according to a friend) engineers tables while holding a schematic.
