### ISSUE TITLE
custom trees

### ISSUE THREAD

**Issue by resinate** [thraaawn/BonsaiTrees#97]
im trying to make a custom tree but i dont know how to link shape.d file to types.d i get the tree growing in game but its invisible i havent seen any utube tut videos on it

**Comment by thraaawn** [comment]
Which step in the readme did not work for you? Your question is not making any sense if you followed the guide there.
To answer it anyway: you link a shape to a type by using the unique id of the tree type.

**Comment by resinate** [comment]
what if this sapling doesnt excatly exist? what im doing is making ores grow themselves. i got it to where i put iron ore in and it grows but no custom tree. i made the in game thing.

mytreemod_iron_tree001.json

-------------------------------------
  "type": "mytreemod:iron_tree",
  "version": 2,
  "ref": {
    "a": {
      "name": "minecraft:iron_block",
      "meta": 0
    },
    "b": {
      "name": "minecraft:iron_ore",
      "meta": 0
    }
  },
etc.....

**Comment by thraaawn** [comment]
It's a crime to strip indenting from code/data blocks. Stop that. Use pastebin or gists.
Paste the full files, not the stuff you think is important and leave other stuff out. There is absolutely no need reduce the amount of information you are giving. "etc..." in parts that need to be **exact** is not helpful.

> what if this sapling doesnt excatly exist?

You read the manual (again). You can just build the tree shape yourself and use the command from the guide. You obviously did not read the guide. It specifically says:
>Grow a few of your trees or build a structure resembling your tree (maybe you want to grow bonsai redstone crystals?).

**Comment by resinate** [comment]
thanks ill have a look into the logs.
