### ISSUE TITLE
Miner Bug:  Hopper Planter Always light gray after use...

### ISSUE THREAD

**Issue by ArkavianX** [thraaawn/BonsaiTrees#98]
This is in: 

MC 1.12.2 - Skyblock 4

When you make a bonsai hopper plot (the tier 2), it has no color, but once placed upon a chest it becomes "light gray" 

This isn't much of a bug, but more so an inventory/storage stacking issue.

**Comment by thraaawn** [comment]
Light gray is the default color for bonsai pots.
There are no uncolored pots.
