### ISSUE TITLE
Bonsai trees make lag when the output inventory is full

### ISSUE THREAD

**Issue by ApolloMCC** [thraaawn/BonsaiTrees#99]
Bonsai trees make lag when the output inventory is full.
In a server when multiple players are using them, it starts becoming an issue.

**Comment by thraaawn** [comment]
No they don't. What makes you think they do?
How about you provide some more details instead of stripping away and ignoring the issue template?

**Comment by ApolloMCC** [comment]
Ehhh, how about your read your other issues in your github when multiple people have stated that they do? Also how about you test it? 
It's COMMON knowledge in minecraft that when an entity is trying to fill a full inventory it stresses the server more than normal.

**Comment by thraaawn** [comment]
Ok. Bye.

**Comment by ApolloMCC** [comment]
#80

**Comment by thraaawn** [comment]
> This is actually a vanilla Hopper issue. You can reproduce the same effects by pointing a hopper into a full inventory and filling the hopper with multiple different types of item stacks.

**Comment by ApolloMCC** [comment]
Yes, you share the same mechanic, but maybe you can do something about it? 
If not it's understandable

**Comment by thraaawn** [comment]
I did do something about it. Stuff is getting voided if the inventory below is full.
This is an *old* issue and has been improved and iterated on multiple times.

**Comment by thraaawn** [comment]
See https://github.com/thraaawn/BonsaiTrees/issues/61
